
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `holidays` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model holidays
 * 
 */
export type holidaysModel = runtime.Types.Result.DefaultSelection<Prisma.$holidaysPayload>

export type AggregateHolidays = {
  _count: HolidaysCountAggregateOutputType | null
  _avg: HolidaysAvgAggregateOutputType | null
  _sum: HolidaysSumAggregateOutputType | null
  _min: HolidaysMinAggregateOutputType | null
  _max: HolidaysMaxAggregateOutputType | null
}

export type HolidaysAvgAggregateOutputType = {
  id: number | null
  target: number | null
}

export type HolidaysSumAggregateOutputType = {
  id: number | null
  target: number | null
}

export type HolidaysMinAggregateOutputType = {
  id: number | null
  holiday: Date | null
  target: number | null
  description: string | null
}

export type HolidaysMaxAggregateOutputType = {
  id: number | null
  holiday: Date | null
  target: number | null
  description: string | null
}

export type HolidaysCountAggregateOutputType = {
  id: number
  holiday: number
  target: number
  description: number
  _all: number
}


export type HolidaysAvgAggregateInputType = {
  id?: true
  target?: true
}

export type HolidaysSumAggregateInputType = {
  id?: true
  target?: true
}

export type HolidaysMinAggregateInputType = {
  id?: true
  holiday?: true
  target?: true
  description?: true
}

export type HolidaysMaxAggregateInputType = {
  id?: true
  holiday?: true
  target?: true
  description?: true
}

export type HolidaysCountAggregateInputType = {
  id?: true
  holiday?: true
  target?: true
  description?: true
  _all?: true
}

export type HolidaysAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which holidays to aggregate.
   */
  where?: Prisma.holidaysWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of holidays to fetch.
   */
  orderBy?: Prisma.holidaysOrderByWithRelationInput | Prisma.holidaysOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.holidaysWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` holidays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` holidays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned holidays
  **/
  _count?: true | HolidaysCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: HolidaysAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: HolidaysSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HolidaysMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HolidaysMaxAggregateInputType
}

export type GetHolidaysAggregateType<T extends HolidaysAggregateArgs> = {
      [P in keyof T & keyof AggregateHolidays]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHolidays[P]>
    : Prisma.GetScalarType<T[P], AggregateHolidays[P]>
}




export type holidaysGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.holidaysWhereInput
  orderBy?: Prisma.holidaysOrderByWithAggregationInput | Prisma.holidaysOrderByWithAggregationInput[]
  by: Prisma.HolidaysScalarFieldEnum[] | Prisma.HolidaysScalarFieldEnum
  having?: Prisma.holidaysScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HolidaysCountAggregateInputType | true
  _avg?: HolidaysAvgAggregateInputType
  _sum?: HolidaysSumAggregateInputType
  _min?: HolidaysMinAggregateInputType
  _max?: HolidaysMaxAggregateInputType
}

export type HolidaysGroupByOutputType = {
  id: number
  holiday: Date
  target: number | null
  description: string
  _count: HolidaysCountAggregateOutputType | null
  _avg: HolidaysAvgAggregateOutputType | null
  _sum: HolidaysSumAggregateOutputType | null
  _min: HolidaysMinAggregateOutputType | null
  _max: HolidaysMaxAggregateOutputType | null
}

export type GetHolidaysGroupByPayload<T extends holidaysGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HolidaysGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HolidaysGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HolidaysGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HolidaysGroupByOutputType[P]>
      }
    >
  >



export type holidaysWhereInput = {
  AND?: Prisma.holidaysWhereInput | Prisma.holidaysWhereInput[]
  OR?: Prisma.holidaysWhereInput[]
  NOT?: Prisma.holidaysWhereInput | Prisma.holidaysWhereInput[]
  id?: Prisma.IntFilter<"holidays"> | number
  holiday?: Prisma.DateTimeFilter<"holidays"> | Date | string
  target?: Prisma.IntNullableFilter<"holidays"> | number | null
  description?: Prisma.StringFilter<"holidays"> | string
}

export type holidaysOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  holiday?: Prisma.SortOrder
  target?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrder
  _relevance?: Prisma.holidaysOrderByRelevanceInput
}

export type holidaysWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.holidaysWhereInput | Prisma.holidaysWhereInput[]
  OR?: Prisma.holidaysWhereInput[]
  NOT?: Prisma.holidaysWhereInput | Prisma.holidaysWhereInput[]
  holiday?: Prisma.DateTimeFilter<"holidays"> | Date | string
  target?: Prisma.IntNullableFilter<"holidays"> | number | null
  description?: Prisma.StringFilter<"holidays"> | string
}, "id">

export type holidaysOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  holiday?: Prisma.SortOrder
  target?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrder
  _count?: Prisma.holidaysCountOrderByAggregateInput
  _avg?: Prisma.holidaysAvgOrderByAggregateInput
  _max?: Prisma.holidaysMaxOrderByAggregateInput
  _min?: Prisma.holidaysMinOrderByAggregateInput
  _sum?: Prisma.holidaysSumOrderByAggregateInput
}

export type holidaysScalarWhereWithAggregatesInput = {
  AND?: Prisma.holidaysScalarWhereWithAggregatesInput | Prisma.holidaysScalarWhereWithAggregatesInput[]
  OR?: Prisma.holidaysScalarWhereWithAggregatesInput[]
  NOT?: Prisma.holidaysScalarWhereWithAggregatesInput | Prisma.holidaysScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"holidays"> | number
  holiday?: Prisma.DateTimeWithAggregatesFilter<"holidays"> | Date | string
  target?: Prisma.IntNullableWithAggregatesFilter<"holidays"> | number | null
  description?: Prisma.StringWithAggregatesFilter<"holidays"> | string
}

export type holidaysCreateInput = {
  holiday: Date | string
  target?: number | null
  description: string
}

export type holidaysUncheckedCreateInput = {
  id?: number
  holiday: Date | string
  target?: number | null
  description: string
}

export type holidaysUpdateInput = {
  holiday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  target?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type holidaysUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  holiday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  target?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type holidaysCreateManyInput = {
  id?: number
  holiday: Date | string
  target?: number | null
  description: string
}

export type holidaysUpdateManyMutationInput = {
  holiday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  target?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type holidaysUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  holiday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  target?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type holidaysOrderByRelevanceInput = {
  fields: Prisma.holidaysOrderByRelevanceFieldEnum | Prisma.holidaysOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type holidaysCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  holiday?: Prisma.SortOrder
  target?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type holidaysAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  target?: Prisma.SortOrder
}

export type holidaysMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  holiday?: Prisma.SortOrder
  target?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type holidaysMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  holiday?: Prisma.SortOrder
  target?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type holidaysSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  target?: Prisma.SortOrder
}



export type holidaysSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  holiday?: boolean
  target?: boolean
  description?: boolean
}, ExtArgs["result"]["holidays"]>



export type holidaysSelectScalar = {
  id?: boolean
  holiday?: boolean
  target?: boolean
  description?: boolean
}

export type holidaysOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "holiday" | "target" | "description", ExtArgs["result"]["holidays"]>

export type $holidaysPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "holidays"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    holiday: Date
    target: number | null
    description: string
  }, ExtArgs["result"]["holidays"]>
  composites: {}
}

export type holidaysGetPayload<S extends boolean | null | undefined | holidaysDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$holidaysPayload, S>

export type holidaysCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<holidaysFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HolidaysCountAggregateInputType | true
  }

export interface holidaysDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['holidays'], meta: { name: 'holidays' } }
  /**
   * Find zero or one Holidays that matches the filter.
   * @param {holidaysFindUniqueArgs} args - Arguments to find a Holidays
   * @example
   * // Get one Holidays
   * const holidays = await prisma.holidays.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends holidaysFindUniqueArgs>(args: Prisma.SelectSubset<T, holidaysFindUniqueArgs<ExtArgs>>): Prisma.Prisma__holidaysClient<runtime.Types.Result.GetResult<Prisma.$holidaysPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Holidays that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {holidaysFindUniqueOrThrowArgs} args - Arguments to find a Holidays
   * @example
   * // Get one Holidays
   * const holidays = await prisma.holidays.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends holidaysFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, holidaysFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__holidaysClient<runtime.Types.Result.GetResult<Prisma.$holidaysPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Holidays that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {holidaysFindFirstArgs} args - Arguments to find a Holidays
   * @example
   * // Get one Holidays
   * const holidays = await prisma.holidays.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends holidaysFindFirstArgs>(args?: Prisma.SelectSubset<T, holidaysFindFirstArgs<ExtArgs>>): Prisma.Prisma__holidaysClient<runtime.Types.Result.GetResult<Prisma.$holidaysPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Holidays that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {holidaysFindFirstOrThrowArgs} args - Arguments to find a Holidays
   * @example
   * // Get one Holidays
   * const holidays = await prisma.holidays.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends holidaysFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, holidaysFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__holidaysClient<runtime.Types.Result.GetResult<Prisma.$holidaysPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Holidays that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {holidaysFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Holidays
   * const holidays = await prisma.holidays.findMany()
   * 
   * // Get first 10 Holidays
   * const holidays = await prisma.holidays.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const holidaysWithIdOnly = await prisma.holidays.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends holidaysFindManyArgs>(args?: Prisma.SelectSubset<T, holidaysFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$holidaysPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Holidays.
   * @param {holidaysCreateArgs} args - Arguments to create a Holidays.
   * @example
   * // Create one Holidays
   * const Holidays = await prisma.holidays.create({
   *   data: {
   *     // ... data to create a Holidays
   *   }
   * })
   * 
   */
  create<T extends holidaysCreateArgs>(args: Prisma.SelectSubset<T, holidaysCreateArgs<ExtArgs>>): Prisma.Prisma__holidaysClient<runtime.Types.Result.GetResult<Prisma.$holidaysPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Holidays.
   * @param {holidaysCreateManyArgs} args - Arguments to create many Holidays.
   * @example
   * // Create many Holidays
   * const holidays = await prisma.holidays.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends holidaysCreateManyArgs>(args?: Prisma.SelectSubset<T, holidaysCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Holidays.
   * @param {holidaysDeleteArgs} args - Arguments to delete one Holidays.
   * @example
   * // Delete one Holidays
   * const Holidays = await prisma.holidays.delete({
   *   where: {
   *     // ... filter to delete one Holidays
   *   }
   * })
   * 
   */
  delete<T extends holidaysDeleteArgs>(args: Prisma.SelectSubset<T, holidaysDeleteArgs<ExtArgs>>): Prisma.Prisma__holidaysClient<runtime.Types.Result.GetResult<Prisma.$holidaysPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Holidays.
   * @param {holidaysUpdateArgs} args - Arguments to update one Holidays.
   * @example
   * // Update one Holidays
   * const holidays = await prisma.holidays.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends holidaysUpdateArgs>(args: Prisma.SelectSubset<T, holidaysUpdateArgs<ExtArgs>>): Prisma.Prisma__holidaysClient<runtime.Types.Result.GetResult<Prisma.$holidaysPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Holidays.
   * @param {holidaysDeleteManyArgs} args - Arguments to filter Holidays to delete.
   * @example
   * // Delete a few Holidays
   * const { count } = await prisma.holidays.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends holidaysDeleteManyArgs>(args?: Prisma.SelectSubset<T, holidaysDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Holidays.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {holidaysUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Holidays
   * const holidays = await prisma.holidays.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends holidaysUpdateManyArgs>(args: Prisma.SelectSubset<T, holidaysUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Holidays.
   * @param {holidaysUpsertArgs} args - Arguments to update or create a Holidays.
   * @example
   * // Update or create a Holidays
   * const holidays = await prisma.holidays.upsert({
   *   create: {
   *     // ... data to create a Holidays
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Holidays we want to update
   *   }
   * })
   */
  upsert<T extends holidaysUpsertArgs>(args: Prisma.SelectSubset<T, holidaysUpsertArgs<ExtArgs>>): Prisma.Prisma__holidaysClient<runtime.Types.Result.GetResult<Prisma.$holidaysPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Holidays.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {holidaysCountArgs} args - Arguments to filter Holidays to count.
   * @example
   * // Count the number of Holidays
   * const count = await prisma.holidays.count({
   *   where: {
   *     // ... the filter for the Holidays we want to count
   *   }
   * })
  **/
  count<T extends holidaysCountArgs>(
    args?: Prisma.Subset<T, holidaysCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HolidaysCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Holidays.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HolidaysAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HolidaysAggregateArgs>(args: Prisma.Subset<T, HolidaysAggregateArgs>): Prisma.PrismaPromise<GetHolidaysAggregateType<T>>

  /**
   * Group by Holidays.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {holidaysGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends holidaysGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: holidaysGroupByArgs['orderBy'] }
      : { orderBy?: holidaysGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, holidaysGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHolidaysGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the holidays model
 */
readonly fields: holidaysFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for holidays.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__holidaysClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the holidays model
 */
export interface holidaysFieldRefs {
  readonly id: Prisma.FieldRef<"holidays", 'Int'>
  readonly holiday: Prisma.FieldRef<"holidays", 'DateTime'>
  readonly target: Prisma.FieldRef<"holidays", 'Int'>
  readonly description: Prisma.FieldRef<"holidays", 'String'>
}
    

// Custom InputTypes
/**
 * holidays findUnique
 */
export type holidaysFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the holidays
   */
  select?: Prisma.holidaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the holidays
   */
  omit?: Prisma.holidaysOmit<ExtArgs> | null
  /**
   * Filter, which holidays to fetch.
   */
  where: Prisma.holidaysWhereUniqueInput
}

/**
 * holidays findUniqueOrThrow
 */
export type holidaysFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the holidays
   */
  select?: Prisma.holidaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the holidays
   */
  omit?: Prisma.holidaysOmit<ExtArgs> | null
  /**
   * Filter, which holidays to fetch.
   */
  where: Prisma.holidaysWhereUniqueInput
}

/**
 * holidays findFirst
 */
export type holidaysFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the holidays
   */
  select?: Prisma.holidaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the holidays
   */
  omit?: Prisma.holidaysOmit<ExtArgs> | null
  /**
   * Filter, which holidays to fetch.
   */
  where?: Prisma.holidaysWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of holidays to fetch.
   */
  orderBy?: Prisma.holidaysOrderByWithRelationInput | Prisma.holidaysOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for holidays.
   */
  cursor?: Prisma.holidaysWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` holidays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` holidays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of holidays.
   */
  distinct?: Prisma.HolidaysScalarFieldEnum | Prisma.HolidaysScalarFieldEnum[]
}

/**
 * holidays findFirstOrThrow
 */
export type holidaysFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the holidays
   */
  select?: Prisma.holidaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the holidays
   */
  omit?: Prisma.holidaysOmit<ExtArgs> | null
  /**
   * Filter, which holidays to fetch.
   */
  where?: Prisma.holidaysWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of holidays to fetch.
   */
  orderBy?: Prisma.holidaysOrderByWithRelationInput | Prisma.holidaysOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for holidays.
   */
  cursor?: Prisma.holidaysWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` holidays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` holidays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of holidays.
   */
  distinct?: Prisma.HolidaysScalarFieldEnum | Prisma.HolidaysScalarFieldEnum[]
}

/**
 * holidays findMany
 */
export type holidaysFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the holidays
   */
  select?: Prisma.holidaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the holidays
   */
  omit?: Prisma.holidaysOmit<ExtArgs> | null
  /**
   * Filter, which holidays to fetch.
   */
  where?: Prisma.holidaysWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of holidays to fetch.
   */
  orderBy?: Prisma.holidaysOrderByWithRelationInput | Prisma.holidaysOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing holidays.
   */
  cursor?: Prisma.holidaysWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` holidays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` holidays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of holidays.
   */
  distinct?: Prisma.HolidaysScalarFieldEnum | Prisma.HolidaysScalarFieldEnum[]
}

/**
 * holidays create
 */
export type holidaysCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the holidays
   */
  select?: Prisma.holidaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the holidays
   */
  omit?: Prisma.holidaysOmit<ExtArgs> | null
  /**
   * The data needed to create a holidays.
   */
  data: Prisma.XOR<Prisma.holidaysCreateInput, Prisma.holidaysUncheckedCreateInput>
}

/**
 * holidays createMany
 */
export type holidaysCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many holidays.
   */
  data: Prisma.holidaysCreateManyInput | Prisma.holidaysCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * holidays update
 */
export type holidaysUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the holidays
   */
  select?: Prisma.holidaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the holidays
   */
  omit?: Prisma.holidaysOmit<ExtArgs> | null
  /**
   * The data needed to update a holidays.
   */
  data: Prisma.XOR<Prisma.holidaysUpdateInput, Prisma.holidaysUncheckedUpdateInput>
  /**
   * Choose, which holidays to update.
   */
  where: Prisma.holidaysWhereUniqueInput
}

/**
 * holidays updateMany
 */
export type holidaysUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update holidays.
   */
  data: Prisma.XOR<Prisma.holidaysUpdateManyMutationInput, Prisma.holidaysUncheckedUpdateManyInput>
  /**
   * Filter which holidays to update
   */
  where?: Prisma.holidaysWhereInput
  /**
   * Limit how many holidays to update.
   */
  limit?: number
}

/**
 * holidays upsert
 */
export type holidaysUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the holidays
   */
  select?: Prisma.holidaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the holidays
   */
  omit?: Prisma.holidaysOmit<ExtArgs> | null
  /**
   * The filter to search for the holidays to update in case it exists.
   */
  where: Prisma.holidaysWhereUniqueInput
  /**
   * In case the holidays found by the `where` argument doesn't exist, create a new holidays with this data.
   */
  create: Prisma.XOR<Prisma.holidaysCreateInput, Prisma.holidaysUncheckedCreateInput>
  /**
   * In case the holidays was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.holidaysUpdateInput, Prisma.holidaysUncheckedUpdateInput>
}

/**
 * holidays delete
 */
export type holidaysDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the holidays
   */
  select?: Prisma.holidaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the holidays
   */
  omit?: Prisma.holidaysOmit<ExtArgs> | null
  /**
   * Filter which holidays to delete.
   */
  where: Prisma.holidaysWhereUniqueInput
}

/**
 * holidays deleteMany
 */
export type holidaysDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which holidays to delete
   */
  where?: Prisma.holidaysWhereInput
  /**
   * Limit how many holidays to delete.
   */
  limit?: number
}

/**
 * holidays without action
 */
export type holidaysDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the holidays
   */
  select?: Prisma.holidaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the holidays
   */
  omit?: Prisma.holidaysOmit<ExtArgs> | null
}
