
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `patients` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model patients
 * 
 */
export type patientsModel = runtime.Types.Result.DefaultSelection<Prisma.$patientsPayload>

export type AggregatePatients = {
  _count: PatientsCountAggregateOutputType | null
  _avg: PatientsAvgAggregateOutputType | null
  _sum: PatientsSumAggregateOutputType | null
  _min: PatientsMinAggregateOutputType | null
  _max: PatientsMaxAggregateOutputType | null
}

export type PatientsAvgAggregateOutputType = {
  id: number | null
  user_id: number | null
  owner_user_id: number | null
}

export type PatientsSumAggregateOutputType = {
  id: number | null
  user_id: number | null
  owner_user_id: number | null
}

export type PatientsMinAggregateOutputType = {
  id: number | null
  user_id: number | null
  owner_user_id: number | null
  relationship: string | null
  fname: string | null
  mname: string | null
  lname: string | null
  email: string | null
  ext_name: string | null
  birth_date: Date | null
  civil_status: string | null
  sex: string | null
  religion: string | null
  nationality: string | null
  occupation: string | null
  lot_no: string | null
  street: string | null
  barangay: string | null
  city: string | null
  province: string | null
  mobile_no: string | null
  spouse_name: string | null
  spouse_address: string | null
  father_name: string | null
  mother_name: string | null
  created_at: Date | null
}

export type PatientsMaxAggregateOutputType = {
  id: number | null
  user_id: number | null
  owner_user_id: number | null
  relationship: string | null
  fname: string | null
  mname: string | null
  lname: string | null
  email: string | null
  ext_name: string | null
  birth_date: Date | null
  civil_status: string | null
  sex: string | null
  religion: string | null
  nationality: string | null
  occupation: string | null
  lot_no: string | null
  street: string | null
  barangay: string | null
  city: string | null
  province: string | null
  mobile_no: string | null
  spouse_name: string | null
  spouse_address: string | null
  father_name: string | null
  mother_name: string | null
  created_at: Date | null
}

export type PatientsCountAggregateOutputType = {
  id: number
  user_id: number
  owner_user_id: number
  relationship: number
  fname: number
  mname: number
  lname: number
  email: number
  ext_name: number
  birth_date: number
  civil_status: number
  sex: number
  religion: number
  nationality: number
  occupation: number
  lot_no: number
  street: number
  barangay: number
  city: number
  province: number
  mobile_no: number
  spouse_name: number
  spouse_address: number
  father_name: number
  mother_name: number
  created_at: number
  _all: number
}


export type PatientsAvgAggregateInputType = {
  id?: true
  user_id?: true
  owner_user_id?: true
}

export type PatientsSumAggregateInputType = {
  id?: true
  user_id?: true
  owner_user_id?: true
}

export type PatientsMinAggregateInputType = {
  id?: true
  user_id?: true
  owner_user_id?: true
  relationship?: true
  fname?: true
  mname?: true
  lname?: true
  email?: true
  ext_name?: true
  birth_date?: true
  civil_status?: true
  sex?: true
  religion?: true
  nationality?: true
  occupation?: true
  lot_no?: true
  street?: true
  barangay?: true
  city?: true
  province?: true
  mobile_no?: true
  spouse_name?: true
  spouse_address?: true
  father_name?: true
  mother_name?: true
  created_at?: true
}

export type PatientsMaxAggregateInputType = {
  id?: true
  user_id?: true
  owner_user_id?: true
  relationship?: true
  fname?: true
  mname?: true
  lname?: true
  email?: true
  ext_name?: true
  birth_date?: true
  civil_status?: true
  sex?: true
  religion?: true
  nationality?: true
  occupation?: true
  lot_no?: true
  street?: true
  barangay?: true
  city?: true
  province?: true
  mobile_no?: true
  spouse_name?: true
  spouse_address?: true
  father_name?: true
  mother_name?: true
  created_at?: true
}

export type PatientsCountAggregateInputType = {
  id?: true
  user_id?: true
  owner_user_id?: true
  relationship?: true
  fname?: true
  mname?: true
  lname?: true
  email?: true
  ext_name?: true
  birth_date?: true
  civil_status?: true
  sex?: true
  religion?: true
  nationality?: true
  occupation?: true
  lot_no?: true
  street?: true
  barangay?: true
  city?: true
  province?: true
  mobile_no?: true
  spouse_name?: true
  spouse_address?: true
  father_name?: true
  mother_name?: true
  created_at?: true
  _all?: true
}

export type PatientsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which patients to aggregate.
   */
  where?: Prisma.patientsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of patients to fetch.
   */
  orderBy?: Prisma.patientsOrderByWithRelationInput | Prisma.patientsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.patientsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` patients from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` patients.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned patients
  **/
  _count?: true | PatientsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PatientsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PatientsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PatientsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PatientsMaxAggregateInputType
}

export type GetPatientsAggregateType<T extends PatientsAggregateArgs> = {
      [P in keyof T & keyof AggregatePatients]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePatients[P]>
    : Prisma.GetScalarType<T[P], AggregatePatients[P]>
}




export type patientsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.patientsWhereInput
  orderBy?: Prisma.patientsOrderByWithAggregationInput | Prisma.patientsOrderByWithAggregationInput[]
  by: Prisma.PatientsScalarFieldEnum[] | Prisma.PatientsScalarFieldEnum
  having?: Prisma.patientsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PatientsCountAggregateInputType | true
  _avg?: PatientsAvgAggregateInputType
  _sum?: PatientsSumAggregateInputType
  _min?: PatientsMinAggregateInputType
  _max?: PatientsMaxAggregateInputType
}

export type PatientsGroupByOutputType = {
  id: number
  user_id: number | null
  owner_user_id: number | null
  relationship: string | null
  fname: string
  mname: string | null
  lname: string
  email: string | null
  ext_name: string | null
  birth_date: Date
  civil_status: string
  sex: string
  religion: string
  nationality: string
  occupation: string
  lot_no: string
  street: string
  barangay: string
  city: string
  province: string
  mobile_no: string
  spouse_name: string | null
  spouse_address: string | null
  father_name: string
  mother_name: string
  created_at: Date
  _count: PatientsCountAggregateOutputType | null
  _avg: PatientsAvgAggregateOutputType | null
  _sum: PatientsSumAggregateOutputType | null
  _min: PatientsMinAggregateOutputType | null
  _max: PatientsMaxAggregateOutputType | null
}

export type GetPatientsGroupByPayload<T extends patientsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PatientsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PatientsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PatientsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PatientsGroupByOutputType[P]>
      }
    >
  >



export type patientsWhereInput = {
  AND?: Prisma.patientsWhereInput | Prisma.patientsWhereInput[]
  OR?: Prisma.patientsWhereInput[]
  NOT?: Prisma.patientsWhereInput | Prisma.patientsWhereInput[]
  id?: Prisma.IntFilter<"patients"> | number
  user_id?: Prisma.IntNullableFilter<"patients"> | number | null
  owner_user_id?: Prisma.IntNullableFilter<"patients"> | number | null
  relationship?: Prisma.StringNullableFilter<"patients"> | string | null
  fname?: Prisma.StringFilter<"patients"> | string
  mname?: Prisma.StringNullableFilter<"patients"> | string | null
  lname?: Prisma.StringFilter<"patients"> | string
  email?: Prisma.StringNullableFilter<"patients"> | string | null
  ext_name?: Prisma.StringNullableFilter<"patients"> | string | null
  birth_date?: Prisma.DateTimeFilter<"patients"> | Date | string
  civil_status?: Prisma.StringFilter<"patients"> | string
  sex?: Prisma.StringFilter<"patients"> | string
  religion?: Prisma.StringFilter<"patients"> | string
  nationality?: Prisma.StringFilter<"patients"> | string
  occupation?: Prisma.StringFilter<"patients"> | string
  lot_no?: Prisma.StringFilter<"patients"> | string
  street?: Prisma.StringFilter<"patients"> | string
  barangay?: Prisma.StringFilter<"patients"> | string
  city?: Prisma.StringFilter<"patients"> | string
  province?: Prisma.StringFilter<"patients"> | string
  mobile_no?: Prisma.StringFilter<"patients"> | string
  spouse_name?: Prisma.StringNullableFilter<"patients"> | string | null
  spouse_address?: Prisma.StringNullableFilter<"patients"> | string | null
  father_name?: Prisma.StringFilter<"patients"> | string
  mother_name?: Prisma.StringFilter<"patients"> | string
  created_at?: Prisma.DateTimeFilter<"patients"> | Date | string
  appointments?: Prisma.AppointmentsListRelationFilter
}

export type patientsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  owner_user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  relationship?: Prisma.SortOrderInput | Prisma.SortOrder
  fname?: Prisma.SortOrder
  mname?: Prisma.SortOrderInput | Prisma.SortOrder
  lname?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  ext_name?: Prisma.SortOrderInput | Prisma.SortOrder
  birth_date?: Prisma.SortOrder
  civil_status?: Prisma.SortOrder
  sex?: Prisma.SortOrder
  religion?: Prisma.SortOrder
  nationality?: Prisma.SortOrder
  occupation?: Prisma.SortOrder
  lot_no?: Prisma.SortOrder
  street?: Prisma.SortOrder
  barangay?: Prisma.SortOrder
  city?: Prisma.SortOrder
  province?: Prisma.SortOrder
  mobile_no?: Prisma.SortOrder
  spouse_name?: Prisma.SortOrderInput | Prisma.SortOrder
  spouse_address?: Prisma.SortOrderInput | Prisma.SortOrder
  father_name?: Prisma.SortOrder
  mother_name?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  appointments?: Prisma.appointmentsOrderByRelationAggregateInput
  _relevance?: Prisma.patientsOrderByRelevanceInput
}

export type patientsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  user_id?: number
  AND?: Prisma.patientsWhereInput | Prisma.patientsWhereInput[]
  OR?: Prisma.patientsWhereInput[]
  NOT?: Prisma.patientsWhereInput | Prisma.patientsWhereInput[]
  owner_user_id?: Prisma.IntNullableFilter<"patients"> | number | null
  relationship?: Prisma.StringNullableFilter<"patients"> | string | null
  fname?: Prisma.StringFilter<"patients"> | string
  mname?: Prisma.StringNullableFilter<"patients"> | string | null
  lname?: Prisma.StringFilter<"patients"> | string
  email?: Prisma.StringNullableFilter<"patients"> | string | null
  ext_name?: Prisma.StringNullableFilter<"patients"> | string | null
  birth_date?: Prisma.DateTimeFilter<"patients"> | Date | string
  civil_status?: Prisma.StringFilter<"patients"> | string
  sex?: Prisma.StringFilter<"patients"> | string
  religion?: Prisma.StringFilter<"patients"> | string
  nationality?: Prisma.StringFilter<"patients"> | string
  occupation?: Prisma.StringFilter<"patients"> | string
  lot_no?: Prisma.StringFilter<"patients"> | string
  street?: Prisma.StringFilter<"patients"> | string
  barangay?: Prisma.StringFilter<"patients"> | string
  city?: Prisma.StringFilter<"patients"> | string
  province?: Prisma.StringFilter<"patients"> | string
  mobile_no?: Prisma.StringFilter<"patients"> | string
  spouse_name?: Prisma.StringNullableFilter<"patients"> | string | null
  spouse_address?: Prisma.StringNullableFilter<"patients"> | string | null
  father_name?: Prisma.StringFilter<"patients"> | string
  mother_name?: Prisma.StringFilter<"patients"> | string
  created_at?: Prisma.DateTimeFilter<"patients"> | Date | string
  appointments?: Prisma.AppointmentsListRelationFilter
}, "id" | "user_id">

export type patientsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  owner_user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  relationship?: Prisma.SortOrderInput | Prisma.SortOrder
  fname?: Prisma.SortOrder
  mname?: Prisma.SortOrderInput | Prisma.SortOrder
  lname?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  ext_name?: Prisma.SortOrderInput | Prisma.SortOrder
  birth_date?: Prisma.SortOrder
  civil_status?: Prisma.SortOrder
  sex?: Prisma.SortOrder
  religion?: Prisma.SortOrder
  nationality?: Prisma.SortOrder
  occupation?: Prisma.SortOrder
  lot_no?: Prisma.SortOrder
  street?: Prisma.SortOrder
  barangay?: Prisma.SortOrder
  city?: Prisma.SortOrder
  province?: Prisma.SortOrder
  mobile_no?: Prisma.SortOrder
  spouse_name?: Prisma.SortOrderInput | Prisma.SortOrder
  spouse_address?: Prisma.SortOrderInput | Prisma.SortOrder
  father_name?: Prisma.SortOrder
  mother_name?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.patientsCountOrderByAggregateInput
  _avg?: Prisma.patientsAvgOrderByAggregateInput
  _max?: Prisma.patientsMaxOrderByAggregateInput
  _min?: Prisma.patientsMinOrderByAggregateInput
  _sum?: Prisma.patientsSumOrderByAggregateInput
}

export type patientsScalarWhereWithAggregatesInput = {
  AND?: Prisma.patientsScalarWhereWithAggregatesInput | Prisma.patientsScalarWhereWithAggregatesInput[]
  OR?: Prisma.patientsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.patientsScalarWhereWithAggregatesInput | Prisma.patientsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"patients"> | number
  user_id?: Prisma.IntNullableWithAggregatesFilter<"patients"> | number | null
  owner_user_id?: Prisma.IntNullableWithAggregatesFilter<"patients"> | number | null
  relationship?: Prisma.StringNullableWithAggregatesFilter<"patients"> | string | null
  fname?: Prisma.StringWithAggregatesFilter<"patients"> | string
  mname?: Prisma.StringNullableWithAggregatesFilter<"patients"> | string | null
  lname?: Prisma.StringWithAggregatesFilter<"patients"> | string
  email?: Prisma.StringNullableWithAggregatesFilter<"patients"> | string | null
  ext_name?: Prisma.StringNullableWithAggregatesFilter<"patients"> | string | null
  birth_date?: Prisma.DateTimeWithAggregatesFilter<"patients"> | Date | string
  civil_status?: Prisma.StringWithAggregatesFilter<"patients"> | string
  sex?: Prisma.StringWithAggregatesFilter<"patients"> | string
  religion?: Prisma.StringWithAggregatesFilter<"patients"> | string
  nationality?: Prisma.StringWithAggregatesFilter<"patients"> | string
  occupation?: Prisma.StringWithAggregatesFilter<"patients"> | string
  lot_no?: Prisma.StringWithAggregatesFilter<"patients"> | string
  street?: Prisma.StringWithAggregatesFilter<"patients"> | string
  barangay?: Prisma.StringWithAggregatesFilter<"patients"> | string
  city?: Prisma.StringWithAggregatesFilter<"patients"> | string
  province?: Prisma.StringWithAggregatesFilter<"patients"> | string
  mobile_no?: Prisma.StringWithAggregatesFilter<"patients"> | string
  spouse_name?: Prisma.StringNullableWithAggregatesFilter<"patients"> | string | null
  spouse_address?: Prisma.StringNullableWithAggregatesFilter<"patients"> | string | null
  father_name?: Prisma.StringWithAggregatesFilter<"patients"> | string
  mother_name?: Prisma.StringWithAggregatesFilter<"patients"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"patients"> | Date | string
}

export type patientsCreateInput = {
  user_id?: number | null
  owner_user_id?: number | null
  relationship?: string | null
  fname: string
  mname?: string | null
  lname: string
  email?: string | null
  ext_name?: string | null
  birth_date: Date | string
  civil_status: string
  sex?: string
  religion: string
  nationality: string
  occupation: string
  lot_no: string
  street: string
  barangay: string
  city: string
  province: string
  mobile_no: string
  spouse_name?: string | null
  spouse_address?: string | null
  father_name: string
  mother_name: string
  created_at?: Date | string
  appointments?: Prisma.appointmentsCreateNestedManyWithoutPatientInput
}

export type patientsUncheckedCreateInput = {
  id?: number
  user_id?: number | null
  owner_user_id?: number | null
  relationship?: string | null
  fname: string
  mname?: string | null
  lname: string
  email?: string | null
  ext_name?: string | null
  birth_date: Date | string
  civil_status: string
  sex?: string
  religion: string
  nationality: string
  occupation: string
  lot_no: string
  street: string
  barangay: string
  city: string
  province: string
  mobile_no: string
  spouse_name?: string | null
  spouse_address?: string | null
  father_name: string
  mother_name: string
  created_at?: Date | string
  appointments?: Prisma.appointmentsUncheckedCreateNestedManyWithoutPatientInput
}

export type patientsUpdateInput = {
  user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  owner_user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  relationship?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fname?: Prisma.StringFieldUpdateOperationsInput | string
  mname?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lname?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ext_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  birth_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  civil_status?: Prisma.StringFieldUpdateOperationsInput | string
  sex?: Prisma.StringFieldUpdateOperationsInput | string
  religion?: Prisma.StringFieldUpdateOperationsInput | string
  nationality?: Prisma.StringFieldUpdateOperationsInput | string
  occupation?: Prisma.StringFieldUpdateOperationsInput | string
  lot_no?: Prisma.StringFieldUpdateOperationsInput | string
  street?: Prisma.StringFieldUpdateOperationsInput | string
  barangay?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  province?: Prisma.StringFieldUpdateOperationsInput | string
  mobile_no?: Prisma.StringFieldUpdateOperationsInput | string
  spouse_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  spouse_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  father_name?: Prisma.StringFieldUpdateOperationsInput | string
  mother_name?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.appointmentsUpdateManyWithoutPatientNestedInput
}

export type patientsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  owner_user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  relationship?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fname?: Prisma.StringFieldUpdateOperationsInput | string
  mname?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lname?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ext_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  birth_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  civil_status?: Prisma.StringFieldUpdateOperationsInput | string
  sex?: Prisma.StringFieldUpdateOperationsInput | string
  religion?: Prisma.StringFieldUpdateOperationsInput | string
  nationality?: Prisma.StringFieldUpdateOperationsInput | string
  occupation?: Prisma.StringFieldUpdateOperationsInput | string
  lot_no?: Prisma.StringFieldUpdateOperationsInput | string
  street?: Prisma.StringFieldUpdateOperationsInput | string
  barangay?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  province?: Prisma.StringFieldUpdateOperationsInput | string
  mobile_no?: Prisma.StringFieldUpdateOperationsInput | string
  spouse_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  spouse_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  father_name?: Prisma.StringFieldUpdateOperationsInput | string
  mother_name?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.appointmentsUncheckedUpdateManyWithoutPatientNestedInput
}

export type patientsCreateManyInput = {
  id?: number
  user_id?: number | null
  owner_user_id?: number | null
  relationship?: string | null
  fname: string
  mname?: string | null
  lname: string
  email?: string | null
  ext_name?: string | null
  birth_date: Date | string
  civil_status: string
  sex?: string
  religion: string
  nationality: string
  occupation: string
  lot_no: string
  street: string
  barangay: string
  city: string
  province: string
  mobile_no: string
  spouse_name?: string | null
  spouse_address?: string | null
  father_name: string
  mother_name: string
  created_at?: Date | string
}

export type patientsUpdateManyMutationInput = {
  user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  owner_user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  relationship?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fname?: Prisma.StringFieldUpdateOperationsInput | string
  mname?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lname?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ext_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  birth_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  civil_status?: Prisma.StringFieldUpdateOperationsInput | string
  sex?: Prisma.StringFieldUpdateOperationsInput | string
  religion?: Prisma.StringFieldUpdateOperationsInput | string
  nationality?: Prisma.StringFieldUpdateOperationsInput | string
  occupation?: Prisma.StringFieldUpdateOperationsInput | string
  lot_no?: Prisma.StringFieldUpdateOperationsInput | string
  street?: Prisma.StringFieldUpdateOperationsInput | string
  barangay?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  province?: Prisma.StringFieldUpdateOperationsInput | string
  mobile_no?: Prisma.StringFieldUpdateOperationsInput | string
  spouse_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  spouse_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  father_name?: Prisma.StringFieldUpdateOperationsInput | string
  mother_name?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type patientsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  owner_user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  relationship?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fname?: Prisma.StringFieldUpdateOperationsInput | string
  mname?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lname?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ext_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  birth_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  civil_status?: Prisma.StringFieldUpdateOperationsInput | string
  sex?: Prisma.StringFieldUpdateOperationsInput | string
  religion?: Prisma.StringFieldUpdateOperationsInput | string
  nationality?: Prisma.StringFieldUpdateOperationsInput | string
  occupation?: Prisma.StringFieldUpdateOperationsInput | string
  lot_no?: Prisma.StringFieldUpdateOperationsInput | string
  street?: Prisma.StringFieldUpdateOperationsInput | string
  barangay?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  province?: Prisma.StringFieldUpdateOperationsInput | string
  mobile_no?: Prisma.StringFieldUpdateOperationsInput | string
  spouse_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  spouse_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  father_name?: Prisma.StringFieldUpdateOperationsInput | string
  mother_name?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PatientsScalarRelationFilter = {
  is?: Prisma.patientsWhereInput
  isNot?: Prisma.patientsWhereInput
}

export type patientsOrderByRelevanceInput = {
  fields: Prisma.patientsOrderByRelevanceFieldEnum | Prisma.patientsOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type patientsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  owner_user_id?: Prisma.SortOrder
  relationship?: Prisma.SortOrder
  fname?: Prisma.SortOrder
  mname?: Prisma.SortOrder
  lname?: Prisma.SortOrder
  email?: Prisma.SortOrder
  ext_name?: Prisma.SortOrder
  birth_date?: Prisma.SortOrder
  civil_status?: Prisma.SortOrder
  sex?: Prisma.SortOrder
  religion?: Prisma.SortOrder
  nationality?: Prisma.SortOrder
  occupation?: Prisma.SortOrder
  lot_no?: Prisma.SortOrder
  street?: Prisma.SortOrder
  barangay?: Prisma.SortOrder
  city?: Prisma.SortOrder
  province?: Prisma.SortOrder
  mobile_no?: Prisma.SortOrder
  spouse_name?: Prisma.SortOrder
  spouse_address?: Prisma.SortOrder
  father_name?: Prisma.SortOrder
  mother_name?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type patientsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  owner_user_id?: Prisma.SortOrder
}

export type patientsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  owner_user_id?: Prisma.SortOrder
  relationship?: Prisma.SortOrder
  fname?: Prisma.SortOrder
  mname?: Prisma.SortOrder
  lname?: Prisma.SortOrder
  email?: Prisma.SortOrder
  ext_name?: Prisma.SortOrder
  birth_date?: Prisma.SortOrder
  civil_status?: Prisma.SortOrder
  sex?: Prisma.SortOrder
  religion?: Prisma.SortOrder
  nationality?: Prisma.SortOrder
  occupation?: Prisma.SortOrder
  lot_no?: Prisma.SortOrder
  street?: Prisma.SortOrder
  barangay?: Prisma.SortOrder
  city?: Prisma.SortOrder
  province?: Prisma.SortOrder
  mobile_no?: Prisma.SortOrder
  spouse_name?: Prisma.SortOrder
  spouse_address?: Prisma.SortOrder
  father_name?: Prisma.SortOrder
  mother_name?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type patientsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  owner_user_id?: Prisma.SortOrder
  relationship?: Prisma.SortOrder
  fname?: Prisma.SortOrder
  mname?: Prisma.SortOrder
  lname?: Prisma.SortOrder
  email?: Prisma.SortOrder
  ext_name?: Prisma.SortOrder
  birth_date?: Prisma.SortOrder
  civil_status?: Prisma.SortOrder
  sex?: Prisma.SortOrder
  religion?: Prisma.SortOrder
  nationality?: Prisma.SortOrder
  occupation?: Prisma.SortOrder
  lot_no?: Prisma.SortOrder
  street?: Prisma.SortOrder
  barangay?: Prisma.SortOrder
  city?: Prisma.SortOrder
  province?: Prisma.SortOrder
  mobile_no?: Prisma.SortOrder
  spouse_name?: Prisma.SortOrder
  spouse_address?: Prisma.SortOrder
  father_name?: Prisma.SortOrder
  mother_name?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type patientsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  owner_user_id?: Prisma.SortOrder
}

export type patientsCreateNestedOneWithoutAppointmentsInput = {
  create?: Prisma.XOR<Prisma.patientsCreateWithoutAppointmentsInput, Prisma.patientsUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.patientsCreateOrConnectWithoutAppointmentsInput
  connect?: Prisma.patientsWhereUniqueInput
}

export type patientsUpdateOneRequiredWithoutAppointmentsNestedInput = {
  create?: Prisma.XOR<Prisma.patientsCreateWithoutAppointmentsInput, Prisma.patientsUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.patientsCreateOrConnectWithoutAppointmentsInput
  upsert?: Prisma.patientsUpsertWithoutAppointmentsInput
  connect?: Prisma.patientsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.patientsUpdateToOneWithWhereWithoutAppointmentsInput, Prisma.patientsUpdateWithoutAppointmentsInput>, Prisma.patientsUncheckedUpdateWithoutAppointmentsInput>
}

export type patientsCreateWithoutAppointmentsInput = {
  user_id?: number | null
  owner_user_id?: number | null
  relationship?: string | null
  fname: string
  mname?: string | null
  lname: string
  email?: string | null
  ext_name?: string | null
  birth_date: Date | string
  civil_status: string
  sex?: string
  religion: string
  nationality: string
  occupation: string
  lot_no: string
  street: string
  barangay: string
  city: string
  province: string
  mobile_no: string
  spouse_name?: string | null
  spouse_address?: string | null
  father_name: string
  mother_name: string
  created_at?: Date | string
}

export type patientsUncheckedCreateWithoutAppointmentsInput = {
  id?: number
  user_id?: number | null
  owner_user_id?: number | null
  relationship?: string | null
  fname: string
  mname?: string | null
  lname: string
  email?: string | null
  ext_name?: string | null
  birth_date: Date | string
  civil_status: string
  sex?: string
  religion: string
  nationality: string
  occupation: string
  lot_no: string
  street: string
  barangay: string
  city: string
  province: string
  mobile_no: string
  spouse_name?: string | null
  spouse_address?: string | null
  father_name: string
  mother_name: string
  created_at?: Date | string
}

export type patientsCreateOrConnectWithoutAppointmentsInput = {
  where: Prisma.patientsWhereUniqueInput
  create: Prisma.XOR<Prisma.patientsCreateWithoutAppointmentsInput, Prisma.patientsUncheckedCreateWithoutAppointmentsInput>
}

export type patientsUpsertWithoutAppointmentsInput = {
  update: Prisma.XOR<Prisma.patientsUpdateWithoutAppointmentsInput, Prisma.patientsUncheckedUpdateWithoutAppointmentsInput>
  create: Prisma.XOR<Prisma.patientsCreateWithoutAppointmentsInput, Prisma.patientsUncheckedCreateWithoutAppointmentsInput>
  where?: Prisma.patientsWhereInput
}

export type patientsUpdateToOneWithWhereWithoutAppointmentsInput = {
  where?: Prisma.patientsWhereInput
  data: Prisma.XOR<Prisma.patientsUpdateWithoutAppointmentsInput, Prisma.patientsUncheckedUpdateWithoutAppointmentsInput>
}

export type patientsUpdateWithoutAppointmentsInput = {
  user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  owner_user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  relationship?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fname?: Prisma.StringFieldUpdateOperationsInput | string
  mname?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lname?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ext_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  birth_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  civil_status?: Prisma.StringFieldUpdateOperationsInput | string
  sex?: Prisma.StringFieldUpdateOperationsInput | string
  religion?: Prisma.StringFieldUpdateOperationsInput | string
  nationality?: Prisma.StringFieldUpdateOperationsInput | string
  occupation?: Prisma.StringFieldUpdateOperationsInput | string
  lot_no?: Prisma.StringFieldUpdateOperationsInput | string
  street?: Prisma.StringFieldUpdateOperationsInput | string
  barangay?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  province?: Prisma.StringFieldUpdateOperationsInput | string
  mobile_no?: Prisma.StringFieldUpdateOperationsInput | string
  spouse_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  spouse_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  father_name?: Prisma.StringFieldUpdateOperationsInput | string
  mother_name?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type patientsUncheckedUpdateWithoutAppointmentsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  owner_user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  relationship?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fname?: Prisma.StringFieldUpdateOperationsInput | string
  mname?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lname?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ext_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  birth_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  civil_status?: Prisma.StringFieldUpdateOperationsInput | string
  sex?: Prisma.StringFieldUpdateOperationsInput | string
  religion?: Prisma.StringFieldUpdateOperationsInput | string
  nationality?: Prisma.StringFieldUpdateOperationsInput | string
  occupation?: Prisma.StringFieldUpdateOperationsInput | string
  lot_no?: Prisma.StringFieldUpdateOperationsInput | string
  street?: Prisma.StringFieldUpdateOperationsInput | string
  barangay?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  province?: Prisma.StringFieldUpdateOperationsInput | string
  mobile_no?: Prisma.StringFieldUpdateOperationsInput | string
  spouse_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  spouse_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  father_name?: Prisma.StringFieldUpdateOperationsInput | string
  mother_name?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type PatientsCountOutputType
 */

export type PatientsCountOutputType = {
  appointments: number
}

export type PatientsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointments?: boolean | PatientsCountOutputTypeCountAppointmentsArgs
}

/**
 * PatientsCountOutputType without action
 */
export type PatientsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatientsCountOutputType
   */
  select?: Prisma.PatientsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PatientsCountOutputType without action
 */
export type PatientsCountOutputTypeCountAppointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.appointmentsWhereInput
}


export type patientsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  owner_user_id?: boolean
  relationship?: boolean
  fname?: boolean
  mname?: boolean
  lname?: boolean
  email?: boolean
  ext_name?: boolean
  birth_date?: boolean
  civil_status?: boolean
  sex?: boolean
  religion?: boolean
  nationality?: boolean
  occupation?: boolean
  lot_no?: boolean
  street?: boolean
  barangay?: boolean
  city?: boolean
  province?: boolean
  mobile_no?: boolean
  spouse_name?: boolean
  spouse_address?: boolean
  father_name?: boolean
  mother_name?: boolean
  created_at?: boolean
  appointments?: boolean | Prisma.patients$appointmentsArgs<ExtArgs>
  _count?: boolean | Prisma.PatientsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["patients"]>



export type patientsSelectScalar = {
  id?: boolean
  user_id?: boolean
  owner_user_id?: boolean
  relationship?: boolean
  fname?: boolean
  mname?: boolean
  lname?: boolean
  email?: boolean
  ext_name?: boolean
  birth_date?: boolean
  civil_status?: boolean
  sex?: boolean
  religion?: boolean
  nationality?: boolean
  occupation?: boolean
  lot_no?: boolean
  street?: boolean
  barangay?: boolean
  city?: boolean
  province?: boolean
  mobile_no?: boolean
  spouse_name?: boolean
  spouse_address?: boolean
  father_name?: boolean
  mother_name?: boolean
  created_at?: boolean
}

export type patientsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "owner_user_id" | "relationship" | "fname" | "mname" | "lname" | "email" | "ext_name" | "birth_date" | "civil_status" | "sex" | "religion" | "nationality" | "occupation" | "lot_no" | "street" | "barangay" | "city" | "province" | "mobile_no" | "spouse_name" | "spouse_address" | "father_name" | "mother_name" | "created_at", ExtArgs["result"]["patients"]>
export type patientsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointments?: boolean | Prisma.patients$appointmentsArgs<ExtArgs>
  _count?: boolean | Prisma.PatientsCountOutputTypeDefaultArgs<ExtArgs>
}

export type $patientsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "patients"
  objects: {
    appointments: Prisma.$appointmentsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    user_id: number | null
    owner_user_id: number | null
    relationship: string | null
    fname: string
    mname: string | null
    lname: string
    email: string | null
    ext_name: string | null
    birth_date: Date
    civil_status: string
    sex: string
    religion: string
    nationality: string
    occupation: string
    lot_no: string
    street: string
    barangay: string
    city: string
    province: string
    mobile_no: string
    spouse_name: string | null
    spouse_address: string | null
    father_name: string
    mother_name: string
    created_at: Date
  }, ExtArgs["result"]["patients"]>
  composites: {}
}

export type patientsGetPayload<S extends boolean | null | undefined | patientsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$patientsPayload, S>

export type patientsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<patientsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PatientsCountAggregateInputType | true
  }

export interface patientsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['patients'], meta: { name: 'patients' } }
  /**
   * Find zero or one Patients that matches the filter.
   * @param {patientsFindUniqueArgs} args - Arguments to find a Patients
   * @example
   * // Get one Patients
   * const patients = await prisma.patients.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends patientsFindUniqueArgs>(args: Prisma.SelectSubset<T, patientsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__patientsClient<runtime.Types.Result.GetResult<Prisma.$patientsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Patients that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {patientsFindUniqueOrThrowArgs} args - Arguments to find a Patients
   * @example
   * // Get one Patients
   * const patients = await prisma.patients.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends patientsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, patientsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__patientsClient<runtime.Types.Result.GetResult<Prisma.$patientsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Patients that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {patientsFindFirstArgs} args - Arguments to find a Patients
   * @example
   * // Get one Patients
   * const patients = await prisma.patients.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends patientsFindFirstArgs>(args?: Prisma.SelectSubset<T, patientsFindFirstArgs<ExtArgs>>): Prisma.Prisma__patientsClient<runtime.Types.Result.GetResult<Prisma.$patientsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Patients that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {patientsFindFirstOrThrowArgs} args - Arguments to find a Patients
   * @example
   * // Get one Patients
   * const patients = await prisma.patients.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends patientsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, patientsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__patientsClient<runtime.Types.Result.GetResult<Prisma.$patientsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Patients that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {patientsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Patients
   * const patients = await prisma.patients.findMany()
   * 
   * // Get first 10 Patients
   * const patients = await prisma.patients.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const patientsWithIdOnly = await prisma.patients.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends patientsFindManyArgs>(args?: Prisma.SelectSubset<T, patientsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$patientsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Patients.
   * @param {patientsCreateArgs} args - Arguments to create a Patients.
   * @example
   * // Create one Patients
   * const Patients = await prisma.patients.create({
   *   data: {
   *     // ... data to create a Patients
   *   }
   * })
   * 
   */
  create<T extends patientsCreateArgs>(args: Prisma.SelectSubset<T, patientsCreateArgs<ExtArgs>>): Prisma.Prisma__patientsClient<runtime.Types.Result.GetResult<Prisma.$patientsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Patients.
   * @param {patientsCreateManyArgs} args - Arguments to create many Patients.
   * @example
   * // Create many Patients
   * const patients = await prisma.patients.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends patientsCreateManyArgs>(args?: Prisma.SelectSubset<T, patientsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Patients.
   * @param {patientsDeleteArgs} args - Arguments to delete one Patients.
   * @example
   * // Delete one Patients
   * const Patients = await prisma.patients.delete({
   *   where: {
   *     // ... filter to delete one Patients
   *   }
   * })
   * 
   */
  delete<T extends patientsDeleteArgs>(args: Prisma.SelectSubset<T, patientsDeleteArgs<ExtArgs>>): Prisma.Prisma__patientsClient<runtime.Types.Result.GetResult<Prisma.$patientsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Patients.
   * @param {patientsUpdateArgs} args - Arguments to update one Patients.
   * @example
   * // Update one Patients
   * const patients = await prisma.patients.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends patientsUpdateArgs>(args: Prisma.SelectSubset<T, patientsUpdateArgs<ExtArgs>>): Prisma.Prisma__patientsClient<runtime.Types.Result.GetResult<Prisma.$patientsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Patients.
   * @param {patientsDeleteManyArgs} args - Arguments to filter Patients to delete.
   * @example
   * // Delete a few Patients
   * const { count } = await prisma.patients.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends patientsDeleteManyArgs>(args?: Prisma.SelectSubset<T, patientsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Patients.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {patientsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Patients
   * const patients = await prisma.patients.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends patientsUpdateManyArgs>(args: Prisma.SelectSubset<T, patientsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Patients.
   * @param {patientsUpsertArgs} args - Arguments to update or create a Patients.
   * @example
   * // Update or create a Patients
   * const patients = await prisma.patients.upsert({
   *   create: {
   *     // ... data to create a Patients
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Patients we want to update
   *   }
   * })
   */
  upsert<T extends patientsUpsertArgs>(args: Prisma.SelectSubset<T, patientsUpsertArgs<ExtArgs>>): Prisma.Prisma__patientsClient<runtime.Types.Result.GetResult<Prisma.$patientsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Patients.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {patientsCountArgs} args - Arguments to filter Patients to count.
   * @example
   * // Count the number of Patients
   * const count = await prisma.patients.count({
   *   where: {
   *     // ... the filter for the Patients we want to count
   *   }
   * })
  **/
  count<T extends patientsCountArgs>(
    args?: Prisma.Subset<T, patientsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PatientsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Patients.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PatientsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PatientsAggregateArgs>(args: Prisma.Subset<T, PatientsAggregateArgs>): Prisma.PrismaPromise<GetPatientsAggregateType<T>>

  /**
   * Group by Patients.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {patientsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends patientsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: patientsGroupByArgs['orderBy'] }
      : { orderBy?: patientsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, patientsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPatientsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the patients model
 */
readonly fields: patientsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for patients.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__patientsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  appointments<T extends Prisma.patients$appointmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.patients$appointmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$appointmentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the patients model
 */
export interface patientsFieldRefs {
  readonly id: Prisma.FieldRef<"patients", 'Int'>
  readonly user_id: Prisma.FieldRef<"patients", 'Int'>
  readonly owner_user_id: Prisma.FieldRef<"patients", 'Int'>
  readonly relationship: Prisma.FieldRef<"patients", 'String'>
  readonly fname: Prisma.FieldRef<"patients", 'String'>
  readonly mname: Prisma.FieldRef<"patients", 'String'>
  readonly lname: Prisma.FieldRef<"patients", 'String'>
  readonly email: Prisma.FieldRef<"patients", 'String'>
  readonly ext_name: Prisma.FieldRef<"patients", 'String'>
  readonly birth_date: Prisma.FieldRef<"patients", 'DateTime'>
  readonly civil_status: Prisma.FieldRef<"patients", 'String'>
  readonly sex: Prisma.FieldRef<"patients", 'String'>
  readonly religion: Prisma.FieldRef<"patients", 'String'>
  readonly nationality: Prisma.FieldRef<"patients", 'String'>
  readonly occupation: Prisma.FieldRef<"patients", 'String'>
  readonly lot_no: Prisma.FieldRef<"patients", 'String'>
  readonly street: Prisma.FieldRef<"patients", 'String'>
  readonly barangay: Prisma.FieldRef<"patients", 'String'>
  readonly city: Prisma.FieldRef<"patients", 'String'>
  readonly province: Prisma.FieldRef<"patients", 'String'>
  readonly mobile_no: Prisma.FieldRef<"patients", 'String'>
  readonly spouse_name: Prisma.FieldRef<"patients", 'String'>
  readonly spouse_address: Prisma.FieldRef<"patients", 'String'>
  readonly father_name: Prisma.FieldRef<"patients", 'String'>
  readonly mother_name: Prisma.FieldRef<"patients", 'String'>
  readonly created_at: Prisma.FieldRef<"patients", 'DateTime'>
}
    

// Custom InputTypes
/**
 * patients findUnique
 */
export type patientsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patients
   */
  select?: Prisma.patientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patients
   */
  omit?: Prisma.patientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.patientsInclude<ExtArgs> | null
  /**
   * Filter, which patients to fetch.
   */
  where: Prisma.patientsWhereUniqueInput
}

/**
 * patients findUniqueOrThrow
 */
export type patientsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patients
   */
  select?: Prisma.patientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patients
   */
  omit?: Prisma.patientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.patientsInclude<ExtArgs> | null
  /**
   * Filter, which patients to fetch.
   */
  where: Prisma.patientsWhereUniqueInput
}

/**
 * patients findFirst
 */
export type patientsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patients
   */
  select?: Prisma.patientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patients
   */
  omit?: Prisma.patientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.patientsInclude<ExtArgs> | null
  /**
   * Filter, which patients to fetch.
   */
  where?: Prisma.patientsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of patients to fetch.
   */
  orderBy?: Prisma.patientsOrderByWithRelationInput | Prisma.patientsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for patients.
   */
  cursor?: Prisma.patientsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` patients from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` patients.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of patients.
   */
  distinct?: Prisma.PatientsScalarFieldEnum | Prisma.PatientsScalarFieldEnum[]
}

/**
 * patients findFirstOrThrow
 */
export type patientsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patients
   */
  select?: Prisma.patientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patients
   */
  omit?: Prisma.patientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.patientsInclude<ExtArgs> | null
  /**
   * Filter, which patients to fetch.
   */
  where?: Prisma.patientsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of patients to fetch.
   */
  orderBy?: Prisma.patientsOrderByWithRelationInput | Prisma.patientsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for patients.
   */
  cursor?: Prisma.patientsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` patients from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` patients.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of patients.
   */
  distinct?: Prisma.PatientsScalarFieldEnum | Prisma.PatientsScalarFieldEnum[]
}

/**
 * patients findMany
 */
export type patientsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patients
   */
  select?: Prisma.patientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patients
   */
  omit?: Prisma.patientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.patientsInclude<ExtArgs> | null
  /**
   * Filter, which patients to fetch.
   */
  where?: Prisma.patientsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of patients to fetch.
   */
  orderBy?: Prisma.patientsOrderByWithRelationInput | Prisma.patientsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing patients.
   */
  cursor?: Prisma.patientsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` patients from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` patients.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of patients.
   */
  distinct?: Prisma.PatientsScalarFieldEnum | Prisma.PatientsScalarFieldEnum[]
}

/**
 * patients create
 */
export type patientsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patients
   */
  select?: Prisma.patientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patients
   */
  omit?: Prisma.patientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.patientsInclude<ExtArgs> | null
  /**
   * The data needed to create a patients.
   */
  data: Prisma.XOR<Prisma.patientsCreateInput, Prisma.patientsUncheckedCreateInput>
}

/**
 * patients createMany
 */
export type patientsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many patients.
   */
  data: Prisma.patientsCreateManyInput | Prisma.patientsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * patients update
 */
export type patientsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patients
   */
  select?: Prisma.patientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patients
   */
  omit?: Prisma.patientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.patientsInclude<ExtArgs> | null
  /**
   * The data needed to update a patients.
   */
  data: Prisma.XOR<Prisma.patientsUpdateInput, Prisma.patientsUncheckedUpdateInput>
  /**
   * Choose, which patients to update.
   */
  where: Prisma.patientsWhereUniqueInput
}

/**
 * patients updateMany
 */
export type patientsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update patients.
   */
  data: Prisma.XOR<Prisma.patientsUpdateManyMutationInput, Prisma.patientsUncheckedUpdateManyInput>
  /**
   * Filter which patients to update
   */
  where?: Prisma.patientsWhereInput
  /**
   * Limit how many patients to update.
   */
  limit?: number
}

/**
 * patients upsert
 */
export type patientsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patients
   */
  select?: Prisma.patientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patients
   */
  omit?: Prisma.patientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.patientsInclude<ExtArgs> | null
  /**
   * The filter to search for the patients to update in case it exists.
   */
  where: Prisma.patientsWhereUniqueInput
  /**
   * In case the patients found by the `where` argument doesn't exist, create a new patients with this data.
   */
  create: Prisma.XOR<Prisma.patientsCreateInput, Prisma.patientsUncheckedCreateInput>
  /**
   * In case the patients was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.patientsUpdateInput, Prisma.patientsUncheckedUpdateInput>
}

/**
 * patients delete
 */
export type patientsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patients
   */
  select?: Prisma.patientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patients
   */
  omit?: Prisma.patientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.patientsInclude<ExtArgs> | null
  /**
   * Filter which patients to delete.
   */
  where: Prisma.patientsWhereUniqueInput
}

/**
 * patients deleteMany
 */
export type patientsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which patients to delete
   */
  where?: Prisma.patientsWhereInput
  /**
   * Limit how many patients to delete.
   */
  limit?: number
}

/**
 * patients.appointments
 */
export type patients$appointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the appointments
   */
  select?: Prisma.appointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the appointments
   */
  omit?: Prisma.appointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.appointmentsInclude<ExtArgs> | null
  where?: Prisma.appointmentsWhereInput
  orderBy?: Prisma.appointmentsOrderByWithRelationInput | Prisma.appointmentsOrderByWithRelationInput[]
  cursor?: Prisma.appointmentsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AppointmentsScalarFieldEnum | Prisma.AppointmentsScalarFieldEnum[]
}

/**
 * patients without action
 */
export type patientsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patients
   */
  select?: Prisma.patientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patients
   */
  omit?: Prisma.patientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.patientsInclude<ExtArgs> | null
}
