
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `patient_dependents` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model patient_dependents
 * 
 */
export type patient_dependentsModel = runtime.Types.Result.DefaultSelection<Prisma.$patient_dependentsPayload>

export type AggregatePatient_dependents = {
  _count: Patient_dependentsCountAggregateOutputType | null
  _avg: Patient_dependentsAvgAggregateOutputType | null
  _sum: Patient_dependentsSumAggregateOutputType | null
  _min: Patient_dependentsMinAggregateOutputType | null
  _max: Patient_dependentsMaxAggregateOutputType | null
}

export type Patient_dependentsAvgAggregateOutputType = {
  id: number | null
  user_id: number | null
  patient_id: number | null
}

export type Patient_dependentsSumAggregateOutputType = {
  id: number | null
  user_id: number | null
  patient_id: number | null
}

export type Patient_dependentsMinAggregateOutputType = {
  id: number | null
  user_id: number | null
  patient_id: number | null
}

export type Patient_dependentsMaxAggregateOutputType = {
  id: number | null
  user_id: number | null
  patient_id: number | null
}

export type Patient_dependentsCountAggregateOutputType = {
  id: number
  user_id: number
  patient_id: number
  _all: number
}


export type Patient_dependentsAvgAggregateInputType = {
  id?: true
  user_id?: true
  patient_id?: true
}

export type Patient_dependentsSumAggregateInputType = {
  id?: true
  user_id?: true
  patient_id?: true
}

export type Patient_dependentsMinAggregateInputType = {
  id?: true
  user_id?: true
  patient_id?: true
}

export type Patient_dependentsMaxAggregateInputType = {
  id?: true
  user_id?: true
  patient_id?: true
}

export type Patient_dependentsCountAggregateInputType = {
  id?: true
  user_id?: true
  patient_id?: true
  _all?: true
}

export type Patient_dependentsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which patient_dependents to aggregate.
   */
  where?: Prisma.patient_dependentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of patient_dependents to fetch.
   */
  orderBy?: Prisma.patient_dependentsOrderByWithRelationInput | Prisma.patient_dependentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.patient_dependentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` patient_dependents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` patient_dependents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned patient_dependents
  **/
  _count?: true | Patient_dependentsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Patient_dependentsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Patient_dependentsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Patient_dependentsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Patient_dependentsMaxAggregateInputType
}

export type GetPatient_dependentsAggregateType<T extends Patient_dependentsAggregateArgs> = {
      [P in keyof T & keyof AggregatePatient_dependents]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePatient_dependents[P]>
    : Prisma.GetScalarType<T[P], AggregatePatient_dependents[P]>
}




export type patient_dependentsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.patient_dependentsWhereInput
  orderBy?: Prisma.patient_dependentsOrderByWithAggregationInput | Prisma.patient_dependentsOrderByWithAggregationInput[]
  by: Prisma.Patient_dependentsScalarFieldEnum[] | Prisma.Patient_dependentsScalarFieldEnum
  having?: Prisma.patient_dependentsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Patient_dependentsCountAggregateInputType | true
  _avg?: Patient_dependentsAvgAggregateInputType
  _sum?: Patient_dependentsSumAggregateInputType
  _min?: Patient_dependentsMinAggregateInputType
  _max?: Patient_dependentsMaxAggregateInputType
}

export type Patient_dependentsGroupByOutputType = {
  id: number
  user_id: number
  patient_id: number
  _count: Patient_dependentsCountAggregateOutputType | null
  _avg: Patient_dependentsAvgAggregateOutputType | null
  _sum: Patient_dependentsSumAggregateOutputType | null
  _min: Patient_dependentsMinAggregateOutputType | null
  _max: Patient_dependentsMaxAggregateOutputType | null
}

export type GetPatient_dependentsGroupByPayload<T extends patient_dependentsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Patient_dependentsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Patient_dependentsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Patient_dependentsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Patient_dependentsGroupByOutputType[P]>
      }
    >
  >



export type patient_dependentsWhereInput = {
  AND?: Prisma.patient_dependentsWhereInput | Prisma.patient_dependentsWhereInput[]
  OR?: Prisma.patient_dependentsWhereInput[]
  NOT?: Prisma.patient_dependentsWhereInput | Prisma.patient_dependentsWhereInput[]
  id?: Prisma.IntFilter<"patient_dependents"> | number
  user_id?: Prisma.IntFilter<"patient_dependents"> | number
  patient_id?: Prisma.IntFilter<"patient_dependents"> | number
}

export type patient_dependentsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  patient_id?: Prisma.SortOrder
}

export type patient_dependentsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.patient_dependentsWhereInput | Prisma.patient_dependentsWhereInput[]
  OR?: Prisma.patient_dependentsWhereInput[]
  NOT?: Prisma.patient_dependentsWhereInput | Prisma.patient_dependentsWhereInput[]
  user_id?: Prisma.IntFilter<"patient_dependents"> | number
  patient_id?: Prisma.IntFilter<"patient_dependents"> | number
}, "id">

export type patient_dependentsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  patient_id?: Prisma.SortOrder
  _count?: Prisma.patient_dependentsCountOrderByAggregateInput
  _avg?: Prisma.patient_dependentsAvgOrderByAggregateInput
  _max?: Prisma.patient_dependentsMaxOrderByAggregateInput
  _min?: Prisma.patient_dependentsMinOrderByAggregateInput
  _sum?: Prisma.patient_dependentsSumOrderByAggregateInput
}

export type patient_dependentsScalarWhereWithAggregatesInput = {
  AND?: Prisma.patient_dependentsScalarWhereWithAggregatesInput | Prisma.patient_dependentsScalarWhereWithAggregatesInput[]
  OR?: Prisma.patient_dependentsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.patient_dependentsScalarWhereWithAggregatesInput | Prisma.patient_dependentsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"patient_dependents"> | number
  user_id?: Prisma.IntWithAggregatesFilter<"patient_dependents"> | number
  patient_id?: Prisma.IntWithAggregatesFilter<"patient_dependents"> | number
}

export type patient_dependentsCreateInput = {
  user_id: number
  patient_id: number
}

export type patient_dependentsUncheckedCreateInput = {
  id?: number
  user_id: number
  patient_id: number
}

export type patient_dependentsUpdateInput = {
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  patient_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type patient_dependentsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  patient_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type patient_dependentsCreateManyInput = {
  id?: number
  user_id: number
  patient_id: number
}

export type patient_dependentsUpdateManyMutationInput = {
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  patient_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type patient_dependentsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  patient_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type patient_dependentsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  patient_id?: Prisma.SortOrder
}

export type patient_dependentsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  patient_id?: Prisma.SortOrder
}

export type patient_dependentsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  patient_id?: Prisma.SortOrder
}

export type patient_dependentsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  patient_id?: Prisma.SortOrder
}

export type patient_dependentsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  patient_id?: Prisma.SortOrder
}



export type patient_dependentsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  patient_id?: boolean
}, ExtArgs["result"]["patient_dependents"]>



export type patient_dependentsSelectScalar = {
  id?: boolean
  user_id?: boolean
  patient_id?: boolean
}

export type patient_dependentsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "patient_id", ExtArgs["result"]["patient_dependents"]>

export type $patient_dependentsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "patient_dependents"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    user_id: number
    patient_id: number
  }, ExtArgs["result"]["patient_dependents"]>
  composites: {}
}

export type patient_dependentsGetPayload<S extends boolean | null | undefined | patient_dependentsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$patient_dependentsPayload, S>

export type patient_dependentsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<patient_dependentsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Patient_dependentsCountAggregateInputType | true
  }

export interface patient_dependentsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['patient_dependents'], meta: { name: 'patient_dependents' } }
  /**
   * Find zero or one Patient_dependents that matches the filter.
   * @param {patient_dependentsFindUniqueArgs} args - Arguments to find a Patient_dependents
   * @example
   * // Get one Patient_dependents
   * const patient_dependents = await prisma.patient_dependents.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends patient_dependentsFindUniqueArgs>(args: Prisma.SelectSubset<T, patient_dependentsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__patient_dependentsClient<runtime.Types.Result.GetResult<Prisma.$patient_dependentsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Patient_dependents that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {patient_dependentsFindUniqueOrThrowArgs} args - Arguments to find a Patient_dependents
   * @example
   * // Get one Patient_dependents
   * const patient_dependents = await prisma.patient_dependents.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends patient_dependentsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, patient_dependentsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__patient_dependentsClient<runtime.Types.Result.GetResult<Prisma.$patient_dependentsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Patient_dependents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {patient_dependentsFindFirstArgs} args - Arguments to find a Patient_dependents
   * @example
   * // Get one Patient_dependents
   * const patient_dependents = await prisma.patient_dependents.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends patient_dependentsFindFirstArgs>(args?: Prisma.SelectSubset<T, patient_dependentsFindFirstArgs<ExtArgs>>): Prisma.Prisma__patient_dependentsClient<runtime.Types.Result.GetResult<Prisma.$patient_dependentsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Patient_dependents that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {patient_dependentsFindFirstOrThrowArgs} args - Arguments to find a Patient_dependents
   * @example
   * // Get one Patient_dependents
   * const patient_dependents = await prisma.patient_dependents.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends patient_dependentsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, patient_dependentsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__patient_dependentsClient<runtime.Types.Result.GetResult<Prisma.$patient_dependentsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Patient_dependents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {patient_dependentsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Patient_dependents
   * const patient_dependents = await prisma.patient_dependents.findMany()
   * 
   * // Get first 10 Patient_dependents
   * const patient_dependents = await prisma.patient_dependents.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const patient_dependentsWithIdOnly = await prisma.patient_dependents.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends patient_dependentsFindManyArgs>(args?: Prisma.SelectSubset<T, patient_dependentsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$patient_dependentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Patient_dependents.
   * @param {patient_dependentsCreateArgs} args - Arguments to create a Patient_dependents.
   * @example
   * // Create one Patient_dependents
   * const Patient_dependents = await prisma.patient_dependents.create({
   *   data: {
   *     // ... data to create a Patient_dependents
   *   }
   * })
   * 
   */
  create<T extends patient_dependentsCreateArgs>(args: Prisma.SelectSubset<T, patient_dependentsCreateArgs<ExtArgs>>): Prisma.Prisma__patient_dependentsClient<runtime.Types.Result.GetResult<Prisma.$patient_dependentsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Patient_dependents.
   * @param {patient_dependentsCreateManyArgs} args - Arguments to create many Patient_dependents.
   * @example
   * // Create many Patient_dependents
   * const patient_dependents = await prisma.patient_dependents.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends patient_dependentsCreateManyArgs>(args?: Prisma.SelectSubset<T, patient_dependentsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Patient_dependents.
   * @param {patient_dependentsDeleteArgs} args - Arguments to delete one Patient_dependents.
   * @example
   * // Delete one Patient_dependents
   * const Patient_dependents = await prisma.patient_dependents.delete({
   *   where: {
   *     // ... filter to delete one Patient_dependents
   *   }
   * })
   * 
   */
  delete<T extends patient_dependentsDeleteArgs>(args: Prisma.SelectSubset<T, patient_dependentsDeleteArgs<ExtArgs>>): Prisma.Prisma__patient_dependentsClient<runtime.Types.Result.GetResult<Prisma.$patient_dependentsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Patient_dependents.
   * @param {patient_dependentsUpdateArgs} args - Arguments to update one Patient_dependents.
   * @example
   * // Update one Patient_dependents
   * const patient_dependents = await prisma.patient_dependents.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends patient_dependentsUpdateArgs>(args: Prisma.SelectSubset<T, patient_dependentsUpdateArgs<ExtArgs>>): Prisma.Prisma__patient_dependentsClient<runtime.Types.Result.GetResult<Prisma.$patient_dependentsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Patient_dependents.
   * @param {patient_dependentsDeleteManyArgs} args - Arguments to filter Patient_dependents to delete.
   * @example
   * // Delete a few Patient_dependents
   * const { count } = await prisma.patient_dependents.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends patient_dependentsDeleteManyArgs>(args?: Prisma.SelectSubset<T, patient_dependentsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Patient_dependents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {patient_dependentsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Patient_dependents
   * const patient_dependents = await prisma.patient_dependents.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends patient_dependentsUpdateManyArgs>(args: Prisma.SelectSubset<T, patient_dependentsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Patient_dependents.
   * @param {patient_dependentsUpsertArgs} args - Arguments to update or create a Patient_dependents.
   * @example
   * // Update or create a Patient_dependents
   * const patient_dependents = await prisma.patient_dependents.upsert({
   *   create: {
   *     // ... data to create a Patient_dependents
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Patient_dependents we want to update
   *   }
   * })
   */
  upsert<T extends patient_dependentsUpsertArgs>(args: Prisma.SelectSubset<T, patient_dependentsUpsertArgs<ExtArgs>>): Prisma.Prisma__patient_dependentsClient<runtime.Types.Result.GetResult<Prisma.$patient_dependentsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Patient_dependents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {patient_dependentsCountArgs} args - Arguments to filter Patient_dependents to count.
   * @example
   * // Count the number of Patient_dependents
   * const count = await prisma.patient_dependents.count({
   *   where: {
   *     // ... the filter for the Patient_dependents we want to count
   *   }
   * })
  **/
  count<T extends patient_dependentsCountArgs>(
    args?: Prisma.Subset<T, patient_dependentsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Patient_dependentsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Patient_dependents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Patient_dependentsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Patient_dependentsAggregateArgs>(args: Prisma.Subset<T, Patient_dependentsAggregateArgs>): Prisma.PrismaPromise<GetPatient_dependentsAggregateType<T>>

  /**
   * Group by Patient_dependents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {patient_dependentsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends patient_dependentsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: patient_dependentsGroupByArgs['orderBy'] }
      : { orderBy?: patient_dependentsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, patient_dependentsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPatient_dependentsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the patient_dependents model
 */
readonly fields: patient_dependentsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for patient_dependents.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__patient_dependentsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the patient_dependents model
 */
export interface patient_dependentsFieldRefs {
  readonly id: Prisma.FieldRef<"patient_dependents", 'Int'>
  readonly user_id: Prisma.FieldRef<"patient_dependents", 'Int'>
  readonly patient_id: Prisma.FieldRef<"patient_dependents", 'Int'>
}
    

// Custom InputTypes
/**
 * patient_dependents findUnique
 */
export type patient_dependentsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patient_dependents
   */
  select?: Prisma.patient_dependentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patient_dependents
   */
  omit?: Prisma.patient_dependentsOmit<ExtArgs> | null
  /**
   * Filter, which patient_dependents to fetch.
   */
  where: Prisma.patient_dependentsWhereUniqueInput
}

/**
 * patient_dependents findUniqueOrThrow
 */
export type patient_dependentsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patient_dependents
   */
  select?: Prisma.patient_dependentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patient_dependents
   */
  omit?: Prisma.patient_dependentsOmit<ExtArgs> | null
  /**
   * Filter, which patient_dependents to fetch.
   */
  where: Prisma.patient_dependentsWhereUniqueInput
}

/**
 * patient_dependents findFirst
 */
export type patient_dependentsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patient_dependents
   */
  select?: Prisma.patient_dependentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patient_dependents
   */
  omit?: Prisma.patient_dependentsOmit<ExtArgs> | null
  /**
   * Filter, which patient_dependents to fetch.
   */
  where?: Prisma.patient_dependentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of patient_dependents to fetch.
   */
  orderBy?: Prisma.patient_dependentsOrderByWithRelationInput | Prisma.patient_dependentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for patient_dependents.
   */
  cursor?: Prisma.patient_dependentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` patient_dependents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` patient_dependents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of patient_dependents.
   */
  distinct?: Prisma.Patient_dependentsScalarFieldEnum | Prisma.Patient_dependentsScalarFieldEnum[]
}

/**
 * patient_dependents findFirstOrThrow
 */
export type patient_dependentsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patient_dependents
   */
  select?: Prisma.patient_dependentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patient_dependents
   */
  omit?: Prisma.patient_dependentsOmit<ExtArgs> | null
  /**
   * Filter, which patient_dependents to fetch.
   */
  where?: Prisma.patient_dependentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of patient_dependents to fetch.
   */
  orderBy?: Prisma.patient_dependentsOrderByWithRelationInput | Prisma.patient_dependentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for patient_dependents.
   */
  cursor?: Prisma.patient_dependentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` patient_dependents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` patient_dependents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of patient_dependents.
   */
  distinct?: Prisma.Patient_dependentsScalarFieldEnum | Prisma.Patient_dependentsScalarFieldEnum[]
}

/**
 * patient_dependents findMany
 */
export type patient_dependentsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patient_dependents
   */
  select?: Prisma.patient_dependentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patient_dependents
   */
  omit?: Prisma.patient_dependentsOmit<ExtArgs> | null
  /**
   * Filter, which patient_dependents to fetch.
   */
  where?: Prisma.patient_dependentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of patient_dependents to fetch.
   */
  orderBy?: Prisma.patient_dependentsOrderByWithRelationInput | Prisma.patient_dependentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing patient_dependents.
   */
  cursor?: Prisma.patient_dependentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` patient_dependents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` patient_dependents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of patient_dependents.
   */
  distinct?: Prisma.Patient_dependentsScalarFieldEnum | Prisma.Patient_dependentsScalarFieldEnum[]
}

/**
 * patient_dependents create
 */
export type patient_dependentsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patient_dependents
   */
  select?: Prisma.patient_dependentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patient_dependents
   */
  omit?: Prisma.patient_dependentsOmit<ExtArgs> | null
  /**
   * The data needed to create a patient_dependents.
   */
  data: Prisma.XOR<Prisma.patient_dependentsCreateInput, Prisma.patient_dependentsUncheckedCreateInput>
}

/**
 * patient_dependents createMany
 */
export type patient_dependentsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many patient_dependents.
   */
  data: Prisma.patient_dependentsCreateManyInput | Prisma.patient_dependentsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * patient_dependents update
 */
export type patient_dependentsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patient_dependents
   */
  select?: Prisma.patient_dependentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patient_dependents
   */
  omit?: Prisma.patient_dependentsOmit<ExtArgs> | null
  /**
   * The data needed to update a patient_dependents.
   */
  data: Prisma.XOR<Prisma.patient_dependentsUpdateInput, Prisma.patient_dependentsUncheckedUpdateInput>
  /**
   * Choose, which patient_dependents to update.
   */
  where: Prisma.patient_dependentsWhereUniqueInput
}

/**
 * patient_dependents updateMany
 */
export type patient_dependentsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update patient_dependents.
   */
  data: Prisma.XOR<Prisma.patient_dependentsUpdateManyMutationInput, Prisma.patient_dependentsUncheckedUpdateManyInput>
  /**
   * Filter which patient_dependents to update
   */
  where?: Prisma.patient_dependentsWhereInput
  /**
   * Limit how many patient_dependents to update.
   */
  limit?: number
}

/**
 * patient_dependents upsert
 */
export type patient_dependentsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patient_dependents
   */
  select?: Prisma.patient_dependentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patient_dependents
   */
  omit?: Prisma.patient_dependentsOmit<ExtArgs> | null
  /**
   * The filter to search for the patient_dependents to update in case it exists.
   */
  where: Prisma.patient_dependentsWhereUniqueInput
  /**
   * In case the patient_dependents found by the `where` argument doesn't exist, create a new patient_dependents with this data.
   */
  create: Prisma.XOR<Prisma.patient_dependentsCreateInput, Prisma.patient_dependentsUncheckedCreateInput>
  /**
   * In case the patient_dependents was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.patient_dependentsUpdateInput, Prisma.patient_dependentsUncheckedUpdateInput>
}

/**
 * patient_dependents delete
 */
export type patient_dependentsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patient_dependents
   */
  select?: Prisma.patient_dependentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patient_dependents
   */
  omit?: Prisma.patient_dependentsOmit<ExtArgs> | null
  /**
   * Filter which patient_dependents to delete.
   */
  where: Prisma.patient_dependentsWhereUniqueInput
}

/**
 * patient_dependents deleteMany
 */
export type patient_dependentsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which patient_dependents to delete
   */
  where?: Prisma.patient_dependentsWhereInput
  /**
   * Limit how many patient_dependents to delete.
   */
  limit?: number
}

/**
 * patient_dependents without action
 */
export type patient_dependentsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the patient_dependents
   */
  select?: Prisma.patient_dependentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the patient_dependents
   */
  omit?: Prisma.patient_dependentsOmit<ExtArgs> | null
}
