
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `queue_session_stat` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model queue_session_stat
 * 
 */
export type queue_session_statModel = runtime.Types.Result.DefaultSelection<Prisma.$queue_session_statPayload>

export type AggregateQueue_session_stat = {
  _count: Queue_session_statCountAggregateOutputType | null
  _avg: Queue_session_statAvgAggregateOutputType | null
  _sum: Queue_session_statSumAggregateOutputType | null
  _min: Queue_session_statMinAggregateOutputType | null
  _max: Queue_session_statMaxAggregateOutputType | null
}

export type Queue_session_statAvgAggregateOutputType = {
  id: number | null
  session_id: number | null
  step: number | null
  now_serving: number | null
  served_count: number | null
  avg_seconds: number | null
}

export type Queue_session_statSumAggregateOutputType = {
  id: number | null
  session_id: number | null
  step: number | null
  now_serving: number | null
  served_count: number | null
  avg_seconds: number | null
}

export type Queue_session_statMinAggregateOutputType = {
  id: number | null
  session_id: number | null
  step: number | null
  now_serving: number | null
  served_sched: string | null
  served_count: number | null
  avg_seconds: number | null
  updated_at: Date | null
}

export type Queue_session_statMaxAggregateOutputType = {
  id: number | null
  session_id: number | null
  step: number | null
  now_serving: number | null
  served_sched: string | null
  served_count: number | null
  avg_seconds: number | null
  updated_at: Date | null
}

export type Queue_session_statCountAggregateOutputType = {
  id: number
  session_id: number
  step: number
  now_serving: number
  served_sched: number
  served_count: number
  avg_seconds: number
  updated_at: number
  _all: number
}


export type Queue_session_statAvgAggregateInputType = {
  id?: true
  session_id?: true
  step?: true
  now_serving?: true
  served_count?: true
  avg_seconds?: true
}

export type Queue_session_statSumAggregateInputType = {
  id?: true
  session_id?: true
  step?: true
  now_serving?: true
  served_count?: true
  avg_seconds?: true
}

export type Queue_session_statMinAggregateInputType = {
  id?: true
  session_id?: true
  step?: true
  now_serving?: true
  served_sched?: true
  served_count?: true
  avg_seconds?: true
  updated_at?: true
}

export type Queue_session_statMaxAggregateInputType = {
  id?: true
  session_id?: true
  step?: true
  now_serving?: true
  served_sched?: true
  served_count?: true
  avg_seconds?: true
  updated_at?: true
}

export type Queue_session_statCountAggregateInputType = {
  id?: true
  session_id?: true
  step?: true
  now_serving?: true
  served_sched?: true
  served_count?: true
  avg_seconds?: true
  updated_at?: true
  _all?: true
}

export type Queue_session_statAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which queue_session_stat to aggregate.
   */
  where?: Prisma.queue_session_statWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of queue_session_stats to fetch.
   */
  orderBy?: Prisma.queue_session_statOrderByWithRelationInput | Prisma.queue_session_statOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.queue_session_statWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` queue_session_stats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` queue_session_stats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned queue_session_stats
  **/
  _count?: true | Queue_session_statCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Queue_session_statAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Queue_session_statSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Queue_session_statMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Queue_session_statMaxAggregateInputType
}

export type GetQueue_session_statAggregateType<T extends Queue_session_statAggregateArgs> = {
      [P in keyof T & keyof AggregateQueue_session_stat]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQueue_session_stat[P]>
    : Prisma.GetScalarType<T[P], AggregateQueue_session_stat[P]>
}




export type queue_session_statGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.queue_session_statWhereInput
  orderBy?: Prisma.queue_session_statOrderByWithAggregationInput | Prisma.queue_session_statOrderByWithAggregationInput[]
  by: Prisma.Queue_session_statScalarFieldEnum[] | Prisma.Queue_session_statScalarFieldEnum
  having?: Prisma.queue_session_statScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Queue_session_statCountAggregateInputType | true
  _avg?: Queue_session_statAvgAggregateInputType
  _sum?: Queue_session_statSumAggregateInputType
  _min?: Queue_session_statMinAggregateInputType
  _max?: Queue_session_statMaxAggregateInputType
}

export type Queue_session_statGroupByOutputType = {
  id: number
  session_id: number
  step: number
  now_serving: number
  served_sched: string | null
  served_count: number
  avg_seconds: number
  updated_at: Date
  _count: Queue_session_statCountAggregateOutputType | null
  _avg: Queue_session_statAvgAggregateOutputType | null
  _sum: Queue_session_statSumAggregateOutputType | null
  _min: Queue_session_statMinAggregateOutputType | null
  _max: Queue_session_statMaxAggregateOutputType | null
}

export type GetQueue_session_statGroupByPayload<T extends queue_session_statGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Queue_session_statGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Queue_session_statGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Queue_session_statGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Queue_session_statGroupByOutputType[P]>
      }
    >
  >



export type queue_session_statWhereInput = {
  AND?: Prisma.queue_session_statWhereInput | Prisma.queue_session_statWhereInput[]
  OR?: Prisma.queue_session_statWhereInput[]
  NOT?: Prisma.queue_session_statWhereInput | Prisma.queue_session_statWhereInput[]
  id?: Prisma.IntFilter<"queue_session_stat"> | number
  session_id?: Prisma.IntFilter<"queue_session_stat"> | number
  step?: Prisma.IntFilter<"queue_session_stat"> | number
  now_serving?: Prisma.IntFilter<"queue_session_stat"> | number
  served_sched?: Prisma.StringNullableFilter<"queue_session_stat"> | string | null
  served_count?: Prisma.IntFilter<"queue_session_stat"> | number
  avg_seconds?: Prisma.FloatFilter<"queue_session_stat"> | number
  updated_at?: Prisma.DateTimeFilter<"queue_session_stat"> | Date | string
  session?: Prisma.XOR<Prisma.Queue_sessionsScalarRelationFilter, Prisma.queue_sessionsWhereInput>
}

export type queue_session_statOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  session_id?: Prisma.SortOrder
  step?: Prisma.SortOrder
  now_serving?: Prisma.SortOrder
  served_sched?: Prisma.SortOrderInput | Prisma.SortOrder
  served_count?: Prisma.SortOrder
  avg_seconds?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  session?: Prisma.queue_sessionsOrderByWithRelationInput
  _relevance?: Prisma.queue_session_statOrderByRelevanceInput
}

export type queue_session_statWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  session_id_step?: Prisma.queue_session_statSession_idStepCompoundUniqueInput
  AND?: Prisma.queue_session_statWhereInput | Prisma.queue_session_statWhereInput[]
  OR?: Prisma.queue_session_statWhereInput[]
  NOT?: Prisma.queue_session_statWhereInput | Prisma.queue_session_statWhereInput[]
  session_id?: Prisma.IntFilter<"queue_session_stat"> | number
  step?: Prisma.IntFilter<"queue_session_stat"> | number
  now_serving?: Prisma.IntFilter<"queue_session_stat"> | number
  served_sched?: Prisma.StringNullableFilter<"queue_session_stat"> | string | null
  served_count?: Prisma.IntFilter<"queue_session_stat"> | number
  avg_seconds?: Prisma.FloatFilter<"queue_session_stat"> | number
  updated_at?: Prisma.DateTimeFilter<"queue_session_stat"> | Date | string
  session?: Prisma.XOR<Prisma.Queue_sessionsScalarRelationFilter, Prisma.queue_sessionsWhereInput>
}, "id" | "session_id_step">

export type queue_session_statOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  session_id?: Prisma.SortOrder
  step?: Prisma.SortOrder
  now_serving?: Prisma.SortOrder
  served_sched?: Prisma.SortOrderInput | Prisma.SortOrder
  served_count?: Prisma.SortOrder
  avg_seconds?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.queue_session_statCountOrderByAggregateInput
  _avg?: Prisma.queue_session_statAvgOrderByAggregateInput
  _max?: Prisma.queue_session_statMaxOrderByAggregateInput
  _min?: Prisma.queue_session_statMinOrderByAggregateInput
  _sum?: Prisma.queue_session_statSumOrderByAggregateInput
}

export type queue_session_statScalarWhereWithAggregatesInput = {
  AND?: Prisma.queue_session_statScalarWhereWithAggregatesInput | Prisma.queue_session_statScalarWhereWithAggregatesInput[]
  OR?: Prisma.queue_session_statScalarWhereWithAggregatesInput[]
  NOT?: Prisma.queue_session_statScalarWhereWithAggregatesInput | Prisma.queue_session_statScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"queue_session_stat"> | number
  session_id?: Prisma.IntWithAggregatesFilter<"queue_session_stat"> | number
  step?: Prisma.IntWithAggregatesFilter<"queue_session_stat"> | number
  now_serving?: Prisma.IntWithAggregatesFilter<"queue_session_stat"> | number
  served_sched?: Prisma.StringNullableWithAggregatesFilter<"queue_session_stat"> | string | null
  served_count?: Prisma.IntWithAggregatesFilter<"queue_session_stat"> | number
  avg_seconds?: Prisma.FloatWithAggregatesFilter<"queue_session_stat"> | number
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"queue_session_stat"> | Date | string
}

export type queue_session_statCreateInput = {
  step: number
  now_serving?: number
  served_sched?: string | null
  served_count?: number
  avg_seconds?: number
  updated_at?: Date | string
  session: Prisma.queue_sessionsCreateNestedOneWithoutStatsInput
}

export type queue_session_statUncheckedCreateInput = {
  id?: number
  session_id: number
  step: number
  now_serving?: number
  served_sched?: string | null
  served_count?: number
  avg_seconds?: number
  updated_at?: Date | string
}

export type queue_session_statUpdateInput = {
  step?: Prisma.IntFieldUpdateOperationsInput | number
  now_serving?: Prisma.IntFieldUpdateOperationsInput | number
  served_sched?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  served_count?: Prisma.IntFieldUpdateOperationsInput | number
  avg_seconds?: Prisma.FloatFieldUpdateOperationsInput | number
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  session?: Prisma.queue_sessionsUpdateOneRequiredWithoutStatsNestedInput
}

export type queue_session_statUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  session_id?: Prisma.IntFieldUpdateOperationsInput | number
  step?: Prisma.IntFieldUpdateOperationsInput | number
  now_serving?: Prisma.IntFieldUpdateOperationsInput | number
  served_sched?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  served_count?: Prisma.IntFieldUpdateOperationsInput | number
  avg_seconds?: Prisma.FloatFieldUpdateOperationsInput | number
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type queue_session_statCreateManyInput = {
  id?: number
  session_id: number
  step: number
  now_serving?: number
  served_sched?: string | null
  served_count?: number
  avg_seconds?: number
  updated_at?: Date | string
}

export type queue_session_statUpdateManyMutationInput = {
  step?: Prisma.IntFieldUpdateOperationsInput | number
  now_serving?: Prisma.IntFieldUpdateOperationsInput | number
  served_sched?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  served_count?: Prisma.IntFieldUpdateOperationsInput | number
  avg_seconds?: Prisma.FloatFieldUpdateOperationsInput | number
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type queue_session_statUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  session_id?: Prisma.IntFieldUpdateOperationsInput | number
  step?: Prisma.IntFieldUpdateOperationsInput | number
  now_serving?: Prisma.IntFieldUpdateOperationsInput | number
  served_sched?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  served_count?: Prisma.IntFieldUpdateOperationsInput | number
  avg_seconds?: Prisma.FloatFieldUpdateOperationsInput | number
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Queue_session_statListRelationFilter = {
  every?: Prisma.queue_session_statWhereInput
  some?: Prisma.queue_session_statWhereInput
  none?: Prisma.queue_session_statWhereInput
}

export type queue_session_statOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type queue_session_statOrderByRelevanceInput = {
  fields: Prisma.queue_session_statOrderByRelevanceFieldEnum | Prisma.queue_session_statOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type queue_session_statSession_idStepCompoundUniqueInput = {
  session_id: number
  step: number
}

export type queue_session_statCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  session_id?: Prisma.SortOrder
  step?: Prisma.SortOrder
  now_serving?: Prisma.SortOrder
  served_sched?: Prisma.SortOrder
  served_count?: Prisma.SortOrder
  avg_seconds?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type queue_session_statAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  session_id?: Prisma.SortOrder
  step?: Prisma.SortOrder
  now_serving?: Prisma.SortOrder
  served_count?: Prisma.SortOrder
  avg_seconds?: Prisma.SortOrder
}

export type queue_session_statMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  session_id?: Prisma.SortOrder
  step?: Prisma.SortOrder
  now_serving?: Prisma.SortOrder
  served_sched?: Prisma.SortOrder
  served_count?: Prisma.SortOrder
  avg_seconds?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type queue_session_statMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  session_id?: Prisma.SortOrder
  step?: Prisma.SortOrder
  now_serving?: Prisma.SortOrder
  served_sched?: Prisma.SortOrder
  served_count?: Prisma.SortOrder
  avg_seconds?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type queue_session_statSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  session_id?: Prisma.SortOrder
  step?: Prisma.SortOrder
  now_serving?: Prisma.SortOrder
  served_count?: Prisma.SortOrder
  avg_seconds?: Prisma.SortOrder
}

export type queue_session_statCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.queue_session_statCreateWithoutSessionInput, Prisma.queue_session_statUncheckedCreateWithoutSessionInput> | Prisma.queue_session_statCreateWithoutSessionInput[] | Prisma.queue_session_statUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.queue_session_statCreateOrConnectWithoutSessionInput | Prisma.queue_session_statCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.queue_session_statCreateManySessionInputEnvelope
  connect?: Prisma.queue_session_statWhereUniqueInput | Prisma.queue_session_statWhereUniqueInput[]
}

export type queue_session_statUncheckedCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.queue_session_statCreateWithoutSessionInput, Prisma.queue_session_statUncheckedCreateWithoutSessionInput> | Prisma.queue_session_statCreateWithoutSessionInput[] | Prisma.queue_session_statUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.queue_session_statCreateOrConnectWithoutSessionInput | Prisma.queue_session_statCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.queue_session_statCreateManySessionInputEnvelope
  connect?: Prisma.queue_session_statWhereUniqueInput | Prisma.queue_session_statWhereUniqueInput[]
}

export type queue_session_statUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.queue_session_statCreateWithoutSessionInput, Prisma.queue_session_statUncheckedCreateWithoutSessionInput> | Prisma.queue_session_statCreateWithoutSessionInput[] | Prisma.queue_session_statUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.queue_session_statCreateOrConnectWithoutSessionInput | Prisma.queue_session_statCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.queue_session_statUpsertWithWhereUniqueWithoutSessionInput | Prisma.queue_session_statUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.queue_session_statCreateManySessionInputEnvelope
  set?: Prisma.queue_session_statWhereUniqueInput | Prisma.queue_session_statWhereUniqueInput[]
  disconnect?: Prisma.queue_session_statWhereUniqueInput | Prisma.queue_session_statWhereUniqueInput[]
  delete?: Prisma.queue_session_statWhereUniqueInput | Prisma.queue_session_statWhereUniqueInput[]
  connect?: Prisma.queue_session_statWhereUniqueInput | Prisma.queue_session_statWhereUniqueInput[]
  update?: Prisma.queue_session_statUpdateWithWhereUniqueWithoutSessionInput | Prisma.queue_session_statUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.queue_session_statUpdateManyWithWhereWithoutSessionInput | Prisma.queue_session_statUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.queue_session_statScalarWhereInput | Prisma.queue_session_statScalarWhereInput[]
}

export type queue_session_statUncheckedUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.queue_session_statCreateWithoutSessionInput, Prisma.queue_session_statUncheckedCreateWithoutSessionInput> | Prisma.queue_session_statCreateWithoutSessionInput[] | Prisma.queue_session_statUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.queue_session_statCreateOrConnectWithoutSessionInput | Prisma.queue_session_statCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.queue_session_statUpsertWithWhereUniqueWithoutSessionInput | Prisma.queue_session_statUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.queue_session_statCreateManySessionInputEnvelope
  set?: Prisma.queue_session_statWhereUniqueInput | Prisma.queue_session_statWhereUniqueInput[]
  disconnect?: Prisma.queue_session_statWhereUniqueInput | Prisma.queue_session_statWhereUniqueInput[]
  delete?: Prisma.queue_session_statWhereUniqueInput | Prisma.queue_session_statWhereUniqueInput[]
  connect?: Prisma.queue_session_statWhereUniqueInput | Prisma.queue_session_statWhereUniqueInput[]
  update?: Prisma.queue_session_statUpdateWithWhereUniqueWithoutSessionInput | Prisma.queue_session_statUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.queue_session_statUpdateManyWithWhereWithoutSessionInput | Prisma.queue_session_statUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.queue_session_statScalarWhereInput | Prisma.queue_session_statScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type queue_session_statCreateWithoutSessionInput = {
  step: number
  now_serving?: number
  served_sched?: string | null
  served_count?: number
  avg_seconds?: number
  updated_at?: Date | string
}

export type queue_session_statUncheckedCreateWithoutSessionInput = {
  id?: number
  step: number
  now_serving?: number
  served_sched?: string | null
  served_count?: number
  avg_seconds?: number
  updated_at?: Date | string
}

export type queue_session_statCreateOrConnectWithoutSessionInput = {
  where: Prisma.queue_session_statWhereUniqueInput
  create: Prisma.XOR<Prisma.queue_session_statCreateWithoutSessionInput, Prisma.queue_session_statUncheckedCreateWithoutSessionInput>
}

export type queue_session_statCreateManySessionInputEnvelope = {
  data: Prisma.queue_session_statCreateManySessionInput | Prisma.queue_session_statCreateManySessionInput[]
  skipDuplicates?: boolean
}

export type queue_session_statUpsertWithWhereUniqueWithoutSessionInput = {
  where: Prisma.queue_session_statWhereUniqueInput
  update: Prisma.XOR<Prisma.queue_session_statUpdateWithoutSessionInput, Prisma.queue_session_statUncheckedUpdateWithoutSessionInput>
  create: Prisma.XOR<Prisma.queue_session_statCreateWithoutSessionInput, Prisma.queue_session_statUncheckedCreateWithoutSessionInput>
}

export type queue_session_statUpdateWithWhereUniqueWithoutSessionInput = {
  where: Prisma.queue_session_statWhereUniqueInput
  data: Prisma.XOR<Prisma.queue_session_statUpdateWithoutSessionInput, Prisma.queue_session_statUncheckedUpdateWithoutSessionInput>
}

export type queue_session_statUpdateManyWithWhereWithoutSessionInput = {
  where: Prisma.queue_session_statScalarWhereInput
  data: Prisma.XOR<Prisma.queue_session_statUpdateManyMutationInput, Prisma.queue_session_statUncheckedUpdateManyWithoutSessionInput>
}

export type queue_session_statScalarWhereInput = {
  AND?: Prisma.queue_session_statScalarWhereInput | Prisma.queue_session_statScalarWhereInput[]
  OR?: Prisma.queue_session_statScalarWhereInput[]
  NOT?: Prisma.queue_session_statScalarWhereInput | Prisma.queue_session_statScalarWhereInput[]
  id?: Prisma.IntFilter<"queue_session_stat"> | number
  session_id?: Prisma.IntFilter<"queue_session_stat"> | number
  step?: Prisma.IntFilter<"queue_session_stat"> | number
  now_serving?: Prisma.IntFilter<"queue_session_stat"> | number
  served_sched?: Prisma.StringNullableFilter<"queue_session_stat"> | string | null
  served_count?: Prisma.IntFilter<"queue_session_stat"> | number
  avg_seconds?: Prisma.FloatFilter<"queue_session_stat"> | number
  updated_at?: Prisma.DateTimeFilter<"queue_session_stat"> | Date | string
}

export type queue_session_statCreateManySessionInput = {
  id?: number
  step: number
  now_serving?: number
  served_sched?: string | null
  served_count?: number
  avg_seconds?: number
  updated_at?: Date | string
}

export type queue_session_statUpdateWithoutSessionInput = {
  step?: Prisma.IntFieldUpdateOperationsInput | number
  now_serving?: Prisma.IntFieldUpdateOperationsInput | number
  served_sched?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  served_count?: Prisma.IntFieldUpdateOperationsInput | number
  avg_seconds?: Prisma.FloatFieldUpdateOperationsInput | number
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type queue_session_statUncheckedUpdateWithoutSessionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  step?: Prisma.IntFieldUpdateOperationsInput | number
  now_serving?: Prisma.IntFieldUpdateOperationsInput | number
  served_sched?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  served_count?: Prisma.IntFieldUpdateOperationsInput | number
  avg_seconds?: Prisma.FloatFieldUpdateOperationsInput | number
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type queue_session_statUncheckedUpdateManyWithoutSessionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  step?: Prisma.IntFieldUpdateOperationsInput | number
  now_serving?: Prisma.IntFieldUpdateOperationsInput | number
  served_sched?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  served_count?: Prisma.IntFieldUpdateOperationsInput | number
  avg_seconds?: Prisma.FloatFieldUpdateOperationsInput | number
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type queue_session_statSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  session_id?: boolean
  step?: boolean
  now_serving?: boolean
  served_sched?: boolean
  served_count?: boolean
  avg_seconds?: boolean
  updated_at?: boolean
  session?: boolean | Prisma.queue_sessionsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["queue_session_stat"]>



export type queue_session_statSelectScalar = {
  id?: boolean
  session_id?: boolean
  step?: boolean
  now_serving?: boolean
  served_sched?: boolean
  served_count?: boolean
  avg_seconds?: boolean
  updated_at?: boolean
}

export type queue_session_statOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "session_id" | "step" | "now_serving" | "served_sched" | "served_count" | "avg_seconds" | "updated_at", ExtArgs["result"]["queue_session_stat"]>
export type queue_session_statInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.queue_sessionsDefaultArgs<ExtArgs>
}

export type $queue_session_statPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "queue_session_stat"
  objects: {
    session: Prisma.$queue_sessionsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    session_id: number
    step: number
    now_serving: number
    served_sched: string | null
    served_count: number
    avg_seconds: number
    updated_at: Date
  }, ExtArgs["result"]["queue_session_stat"]>
  composites: {}
}

export type queue_session_statGetPayload<S extends boolean | null | undefined | queue_session_statDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$queue_session_statPayload, S>

export type queue_session_statCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<queue_session_statFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Queue_session_statCountAggregateInputType | true
  }

export interface queue_session_statDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['queue_session_stat'], meta: { name: 'queue_session_stat' } }
  /**
   * Find zero or one Queue_session_stat that matches the filter.
   * @param {queue_session_statFindUniqueArgs} args - Arguments to find a Queue_session_stat
   * @example
   * // Get one Queue_session_stat
   * const queue_session_stat = await prisma.queue_session_stat.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends queue_session_statFindUniqueArgs>(args: Prisma.SelectSubset<T, queue_session_statFindUniqueArgs<ExtArgs>>): Prisma.Prisma__queue_session_statClient<runtime.Types.Result.GetResult<Prisma.$queue_session_statPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Queue_session_stat that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {queue_session_statFindUniqueOrThrowArgs} args - Arguments to find a Queue_session_stat
   * @example
   * // Get one Queue_session_stat
   * const queue_session_stat = await prisma.queue_session_stat.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends queue_session_statFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, queue_session_statFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__queue_session_statClient<runtime.Types.Result.GetResult<Prisma.$queue_session_statPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Queue_session_stat that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {queue_session_statFindFirstArgs} args - Arguments to find a Queue_session_stat
   * @example
   * // Get one Queue_session_stat
   * const queue_session_stat = await prisma.queue_session_stat.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends queue_session_statFindFirstArgs>(args?: Prisma.SelectSubset<T, queue_session_statFindFirstArgs<ExtArgs>>): Prisma.Prisma__queue_session_statClient<runtime.Types.Result.GetResult<Prisma.$queue_session_statPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Queue_session_stat that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {queue_session_statFindFirstOrThrowArgs} args - Arguments to find a Queue_session_stat
   * @example
   * // Get one Queue_session_stat
   * const queue_session_stat = await prisma.queue_session_stat.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends queue_session_statFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, queue_session_statFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__queue_session_statClient<runtime.Types.Result.GetResult<Prisma.$queue_session_statPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Queue_session_stats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {queue_session_statFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Queue_session_stats
   * const queue_session_stats = await prisma.queue_session_stat.findMany()
   * 
   * // Get first 10 Queue_session_stats
   * const queue_session_stats = await prisma.queue_session_stat.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const queue_session_statWithIdOnly = await prisma.queue_session_stat.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends queue_session_statFindManyArgs>(args?: Prisma.SelectSubset<T, queue_session_statFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$queue_session_statPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Queue_session_stat.
   * @param {queue_session_statCreateArgs} args - Arguments to create a Queue_session_stat.
   * @example
   * // Create one Queue_session_stat
   * const Queue_session_stat = await prisma.queue_session_stat.create({
   *   data: {
   *     // ... data to create a Queue_session_stat
   *   }
   * })
   * 
   */
  create<T extends queue_session_statCreateArgs>(args: Prisma.SelectSubset<T, queue_session_statCreateArgs<ExtArgs>>): Prisma.Prisma__queue_session_statClient<runtime.Types.Result.GetResult<Prisma.$queue_session_statPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Queue_session_stats.
   * @param {queue_session_statCreateManyArgs} args - Arguments to create many Queue_session_stats.
   * @example
   * // Create many Queue_session_stats
   * const queue_session_stat = await prisma.queue_session_stat.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends queue_session_statCreateManyArgs>(args?: Prisma.SelectSubset<T, queue_session_statCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Queue_session_stat.
   * @param {queue_session_statDeleteArgs} args - Arguments to delete one Queue_session_stat.
   * @example
   * // Delete one Queue_session_stat
   * const Queue_session_stat = await prisma.queue_session_stat.delete({
   *   where: {
   *     // ... filter to delete one Queue_session_stat
   *   }
   * })
   * 
   */
  delete<T extends queue_session_statDeleteArgs>(args: Prisma.SelectSubset<T, queue_session_statDeleteArgs<ExtArgs>>): Prisma.Prisma__queue_session_statClient<runtime.Types.Result.GetResult<Prisma.$queue_session_statPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Queue_session_stat.
   * @param {queue_session_statUpdateArgs} args - Arguments to update one Queue_session_stat.
   * @example
   * // Update one Queue_session_stat
   * const queue_session_stat = await prisma.queue_session_stat.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends queue_session_statUpdateArgs>(args: Prisma.SelectSubset<T, queue_session_statUpdateArgs<ExtArgs>>): Prisma.Prisma__queue_session_statClient<runtime.Types.Result.GetResult<Prisma.$queue_session_statPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Queue_session_stats.
   * @param {queue_session_statDeleteManyArgs} args - Arguments to filter Queue_session_stats to delete.
   * @example
   * // Delete a few Queue_session_stats
   * const { count } = await prisma.queue_session_stat.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends queue_session_statDeleteManyArgs>(args?: Prisma.SelectSubset<T, queue_session_statDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Queue_session_stats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {queue_session_statUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Queue_session_stats
   * const queue_session_stat = await prisma.queue_session_stat.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends queue_session_statUpdateManyArgs>(args: Prisma.SelectSubset<T, queue_session_statUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Queue_session_stat.
   * @param {queue_session_statUpsertArgs} args - Arguments to update or create a Queue_session_stat.
   * @example
   * // Update or create a Queue_session_stat
   * const queue_session_stat = await prisma.queue_session_stat.upsert({
   *   create: {
   *     // ... data to create a Queue_session_stat
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Queue_session_stat we want to update
   *   }
   * })
   */
  upsert<T extends queue_session_statUpsertArgs>(args: Prisma.SelectSubset<T, queue_session_statUpsertArgs<ExtArgs>>): Prisma.Prisma__queue_session_statClient<runtime.Types.Result.GetResult<Prisma.$queue_session_statPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Queue_session_stats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {queue_session_statCountArgs} args - Arguments to filter Queue_session_stats to count.
   * @example
   * // Count the number of Queue_session_stats
   * const count = await prisma.queue_session_stat.count({
   *   where: {
   *     // ... the filter for the Queue_session_stats we want to count
   *   }
   * })
  **/
  count<T extends queue_session_statCountArgs>(
    args?: Prisma.Subset<T, queue_session_statCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Queue_session_statCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Queue_session_stat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Queue_session_statAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Queue_session_statAggregateArgs>(args: Prisma.Subset<T, Queue_session_statAggregateArgs>): Prisma.PrismaPromise<GetQueue_session_statAggregateType<T>>

  /**
   * Group by Queue_session_stat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {queue_session_statGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends queue_session_statGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: queue_session_statGroupByArgs['orderBy'] }
      : { orderBy?: queue_session_statGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, queue_session_statGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQueue_session_statGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the queue_session_stat model
 */
readonly fields: queue_session_statFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for queue_session_stat.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__queue_session_statClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  session<T extends Prisma.queue_sessionsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.queue_sessionsDefaultArgs<ExtArgs>>): Prisma.Prisma__queue_sessionsClient<runtime.Types.Result.GetResult<Prisma.$queue_sessionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the queue_session_stat model
 */
export interface queue_session_statFieldRefs {
  readonly id: Prisma.FieldRef<"queue_session_stat", 'Int'>
  readonly session_id: Prisma.FieldRef<"queue_session_stat", 'Int'>
  readonly step: Prisma.FieldRef<"queue_session_stat", 'Int'>
  readonly now_serving: Prisma.FieldRef<"queue_session_stat", 'Int'>
  readonly served_sched: Prisma.FieldRef<"queue_session_stat", 'String'>
  readonly served_count: Prisma.FieldRef<"queue_session_stat", 'Int'>
  readonly avg_seconds: Prisma.FieldRef<"queue_session_stat", 'Float'>
  readonly updated_at: Prisma.FieldRef<"queue_session_stat", 'DateTime'>
}
    

// Custom InputTypes
/**
 * queue_session_stat findUnique
 */
export type queue_session_statFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the queue_session_stat
   */
  select?: Prisma.queue_session_statSelect<ExtArgs> | null
  /**
   * Omit specific fields from the queue_session_stat
   */
  omit?: Prisma.queue_session_statOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.queue_session_statInclude<ExtArgs> | null
  /**
   * Filter, which queue_session_stat to fetch.
   */
  where: Prisma.queue_session_statWhereUniqueInput
}

/**
 * queue_session_stat findUniqueOrThrow
 */
export type queue_session_statFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the queue_session_stat
   */
  select?: Prisma.queue_session_statSelect<ExtArgs> | null
  /**
   * Omit specific fields from the queue_session_stat
   */
  omit?: Prisma.queue_session_statOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.queue_session_statInclude<ExtArgs> | null
  /**
   * Filter, which queue_session_stat to fetch.
   */
  where: Prisma.queue_session_statWhereUniqueInput
}

/**
 * queue_session_stat findFirst
 */
export type queue_session_statFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the queue_session_stat
   */
  select?: Prisma.queue_session_statSelect<ExtArgs> | null
  /**
   * Omit specific fields from the queue_session_stat
   */
  omit?: Prisma.queue_session_statOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.queue_session_statInclude<ExtArgs> | null
  /**
   * Filter, which queue_session_stat to fetch.
   */
  where?: Prisma.queue_session_statWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of queue_session_stats to fetch.
   */
  orderBy?: Prisma.queue_session_statOrderByWithRelationInput | Prisma.queue_session_statOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for queue_session_stats.
   */
  cursor?: Prisma.queue_session_statWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` queue_session_stats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` queue_session_stats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of queue_session_stats.
   */
  distinct?: Prisma.Queue_session_statScalarFieldEnum | Prisma.Queue_session_statScalarFieldEnum[]
}

/**
 * queue_session_stat findFirstOrThrow
 */
export type queue_session_statFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the queue_session_stat
   */
  select?: Prisma.queue_session_statSelect<ExtArgs> | null
  /**
   * Omit specific fields from the queue_session_stat
   */
  omit?: Prisma.queue_session_statOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.queue_session_statInclude<ExtArgs> | null
  /**
   * Filter, which queue_session_stat to fetch.
   */
  where?: Prisma.queue_session_statWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of queue_session_stats to fetch.
   */
  orderBy?: Prisma.queue_session_statOrderByWithRelationInput | Prisma.queue_session_statOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for queue_session_stats.
   */
  cursor?: Prisma.queue_session_statWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` queue_session_stats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` queue_session_stats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of queue_session_stats.
   */
  distinct?: Prisma.Queue_session_statScalarFieldEnum | Prisma.Queue_session_statScalarFieldEnum[]
}

/**
 * queue_session_stat findMany
 */
export type queue_session_statFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the queue_session_stat
   */
  select?: Prisma.queue_session_statSelect<ExtArgs> | null
  /**
   * Omit specific fields from the queue_session_stat
   */
  omit?: Prisma.queue_session_statOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.queue_session_statInclude<ExtArgs> | null
  /**
   * Filter, which queue_session_stats to fetch.
   */
  where?: Prisma.queue_session_statWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of queue_session_stats to fetch.
   */
  orderBy?: Prisma.queue_session_statOrderByWithRelationInput | Prisma.queue_session_statOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing queue_session_stats.
   */
  cursor?: Prisma.queue_session_statWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` queue_session_stats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` queue_session_stats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of queue_session_stats.
   */
  distinct?: Prisma.Queue_session_statScalarFieldEnum | Prisma.Queue_session_statScalarFieldEnum[]
}

/**
 * queue_session_stat create
 */
export type queue_session_statCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the queue_session_stat
   */
  select?: Prisma.queue_session_statSelect<ExtArgs> | null
  /**
   * Omit specific fields from the queue_session_stat
   */
  omit?: Prisma.queue_session_statOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.queue_session_statInclude<ExtArgs> | null
  /**
   * The data needed to create a queue_session_stat.
   */
  data: Prisma.XOR<Prisma.queue_session_statCreateInput, Prisma.queue_session_statUncheckedCreateInput>
}

/**
 * queue_session_stat createMany
 */
export type queue_session_statCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many queue_session_stats.
   */
  data: Prisma.queue_session_statCreateManyInput | Prisma.queue_session_statCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * queue_session_stat update
 */
export type queue_session_statUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the queue_session_stat
   */
  select?: Prisma.queue_session_statSelect<ExtArgs> | null
  /**
   * Omit specific fields from the queue_session_stat
   */
  omit?: Prisma.queue_session_statOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.queue_session_statInclude<ExtArgs> | null
  /**
   * The data needed to update a queue_session_stat.
   */
  data: Prisma.XOR<Prisma.queue_session_statUpdateInput, Prisma.queue_session_statUncheckedUpdateInput>
  /**
   * Choose, which queue_session_stat to update.
   */
  where: Prisma.queue_session_statWhereUniqueInput
}

/**
 * queue_session_stat updateMany
 */
export type queue_session_statUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update queue_session_stats.
   */
  data: Prisma.XOR<Prisma.queue_session_statUpdateManyMutationInput, Prisma.queue_session_statUncheckedUpdateManyInput>
  /**
   * Filter which queue_session_stats to update
   */
  where?: Prisma.queue_session_statWhereInput
  /**
   * Limit how many queue_session_stats to update.
   */
  limit?: number
}

/**
 * queue_session_stat upsert
 */
export type queue_session_statUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the queue_session_stat
   */
  select?: Prisma.queue_session_statSelect<ExtArgs> | null
  /**
   * Omit specific fields from the queue_session_stat
   */
  omit?: Prisma.queue_session_statOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.queue_session_statInclude<ExtArgs> | null
  /**
   * The filter to search for the queue_session_stat to update in case it exists.
   */
  where: Prisma.queue_session_statWhereUniqueInput
  /**
   * In case the queue_session_stat found by the `where` argument doesn't exist, create a new queue_session_stat with this data.
   */
  create: Prisma.XOR<Prisma.queue_session_statCreateInput, Prisma.queue_session_statUncheckedCreateInput>
  /**
   * In case the queue_session_stat was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.queue_session_statUpdateInput, Prisma.queue_session_statUncheckedUpdateInput>
}

/**
 * queue_session_stat delete
 */
export type queue_session_statDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the queue_session_stat
   */
  select?: Prisma.queue_session_statSelect<ExtArgs> | null
  /**
   * Omit specific fields from the queue_session_stat
   */
  omit?: Prisma.queue_session_statOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.queue_session_statInclude<ExtArgs> | null
  /**
   * Filter which queue_session_stat to delete.
   */
  where: Prisma.queue_session_statWhereUniqueInput
}

/**
 * queue_session_stat deleteMany
 */
export type queue_session_statDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which queue_session_stats to delete
   */
  where?: Prisma.queue_session_statWhereInput
  /**
   * Limit how many queue_session_stats to delete.
   */
  limit?: number
}

/**
 * queue_session_stat without action
 */
export type queue_session_statDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the queue_session_stat
   */
  select?: Prisma.queue_session_statSelect<ExtArgs> | null
  /**
   * Omit specific fields from the queue_session_stat
   */
  omit?: Prisma.queue_session_statOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.queue_session_statInclude<ExtArgs> | null
}
