
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `user_access` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model user_access
 * 
 */
export type user_accessModel = runtime.Types.Result.DefaultSelection<Prisma.$user_accessPayload>

export type AggregateUser_access = {
  _count: User_accessCountAggregateOutputType | null
  _avg: User_accessAvgAggregateOutputType | null
  _sum: User_accessSumAggregateOutputType | null
  _min: User_accessMinAggregateOutputType | null
  _max: User_accessMaxAggregateOutputType | null
}

export type User_accessAvgAggregateOutputType = {
  id: number | null
  user_id: number | null
  access_right: number | null
}

export type User_accessSumAggregateOutputType = {
  id: number | null
  user_id: number | null
  access_right: number | null
}

export type User_accessMinAggregateOutputType = {
  id: number | null
  user_id: number | null
  access_right: number | null
}

export type User_accessMaxAggregateOutputType = {
  id: number | null
  user_id: number | null
  access_right: number | null
}

export type User_accessCountAggregateOutputType = {
  id: number
  user_id: number
  departments: number
  access_right: number
  _all: number
}


export type User_accessAvgAggregateInputType = {
  id?: true
  user_id?: true
  access_right?: true
}

export type User_accessSumAggregateInputType = {
  id?: true
  user_id?: true
  access_right?: true
}

export type User_accessMinAggregateInputType = {
  id?: true
  user_id?: true
  access_right?: true
}

export type User_accessMaxAggregateInputType = {
  id?: true
  user_id?: true
  access_right?: true
}

export type User_accessCountAggregateInputType = {
  id?: true
  user_id?: true
  departments?: true
  access_right?: true
  _all?: true
}

export type User_accessAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which user_access to aggregate.
   */
  where?: Prisma.user_accessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_accesses to fetch.
   */
  orderBy?: Prisma.user_accessOrderByWithRelationInput | Prisma.user_accessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.user_accessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_accesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_accesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned user_accesses
  **/
  _count?: true | User_accessCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: User_accessAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: User_accessSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: User_accessMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: User_accessMaxAggregateInputType
}

export type GetUser_accessAggregateType<T extends User_accessAggregateArgs> = {
      [P in keyof T & keyof AggregateUser_access]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser_access[P]>
    : Prisma.GetScalarType<T[P], AggregateUser_access[P]>
}




export type user_accessGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.user_accessWhereInput
  orderBy?: Prisma.user_accessOrderByWithAggregationInput | Prisma.user_accessOrderByWithAggregationInput[]
  by: Prisma.User_accessScalarFieldEnum[] | Prisma.User_accessScalarFieldEnum
  having?: Prisma.user_accessScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: User_accessCountAggregateInputType | true
  _avg?: User_accessAvgAggregateInputType
  _sum?: User_accessSumAggregateInputType
  _min?: User_accessMinAggregateInputType
  _max?: User_accessMaxAggregateInputType
}

export type User_accessGroupByOutputType = {
  id: number
  user_id: number
  departments: runtime.JsonValue | null
  access_right: number
  _count: User_accessCountAggregateOutputType | null
  _avg: User_accessAvgAggregateOutputType | null
  _sum: User_accessSumAggregateOutputType | null
  _min: User_accessMinAggregateOutputType | null
  _max: User_accessMaxAggregateOutputType | null
}

export type GetUser_accessGroupByPayload<T extends user_accessGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<User_accessGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof User_accessGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], User_accessGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], User_accessGroupByOutputType[P]>
      }
    >
  >



export type user_accessWhereInput = {
  AND?: Prisma.user_accessWhereInput | Prisma.user_accessWhereInput[]
  OR?: Prisma.user_accessWhereInput[]
  NOT?: Prisma.user_accessWhereInput | Prisma.user_accessWhereInput[]
  id?: Prisma.IntFilter<"user_access"> | number
  user_id?: Prisma.IntFilter<"user_access"> | number
  departments?: Prisma.JsonNullableFilter<"user_access">
  access_right?: Prisma.IntFilter<"user_access"> | number
}

export type user_accessOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  departments?: Prisma.SortOrderInput | Prisma.SortOrder
  access_right?: Prisma.SortOrder
}

export type user_accessWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  user_id?: number
  AND?: Prisma.user_accessWhereInput | Prisma.user_accessWhereInput[]
  OR?: Prisma.user_accessWhereInput[]
  NOT?: Prisma.user_accessWhereInput | Prisma.user_accessWhereInput[]
  departments?: Prisma.JsonNullableFilter<"user_access">
  access_right?: Prisma.IntFilter<"user_access"> | number
}, "id" | "user_id">

export type user_accessOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  departments?: Prisma.SortOrderInput | Prisma.SortOrder
  access_right?: Prisma.SortOrder
  _count?: Prisma.user_accessCountOrderByAggregateInput
  _avg?: Prisma.user_accessAvgOrderByAggregateInput
  _max?: Prisma.user_accessMaxOrderByAggregateInput
  _min?: Prisma.user_accessMinOrderByAggregateInput
  _sum?: Prisma.user_accessSumOrderByAggregateInput
}

export type user_accessScalarWhereWithAggregatesInput = {
  AND?: Prisma.user_accessScalarWhereWithAggregatesInput | Prisma.user_accessScalarWhereWithAggregatesInput[]
  OR?: Prisma.user_accessScalarWhereWithAggregatesInput[]
  NOT?: Prisma.user_accessScalarWhereWithAggregatesInput | Prisma.user_accessScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"user_access"> | number
  user_id?: Prisma.IntWithAggregatesFilter<"user_access"> | number
  departments?: Prisma.JsonNullableWithAggregatesFilter<"user_access">
  access_right?: Prisma.IntWithAggregatesFilter<"user_access"> | number
}

export type user_accessCreateInput = {
  user_id: number
  departments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  access_right: number
}

export type user_accessUncheckedCreateInput = {
  id?: number
  user_id: number
  departments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  access_right: number
}

export type user_accessUpdateInput = {
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  departments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  access_right?: Prisma.IntFieldUpdateOperationsInput | number
}

export type user_accessUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  departments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  access_right?: Prisma.IntFieldUpdateOperationsInput | number
}

export type user_accessCreateManyInput = {
  id?: number
  user_id: number
  departments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  access_right: number
}

export type user_accessUpdateManyMutationInput = {
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  departments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  access_right?: Prisma.IntFieldUpdateOperationsInput | number
}

export type user_accessUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  departments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  access_right?: Prisma.IntFieldUpdateOperationsInput | number
}

export type user_accessCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  departments?: Prisma.SortOrder
  access_right?: Prisma.SortOrder
}

export type user_accessAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  access_right?: Prisma.SortOrder
}

export type user_accessMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  access_right?: Prisma.SortOrder
}

export type user_accessMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  access_right?: Prisma.SortOrder
}

export type user_accessSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  access_right?: Prisma.SortOrder
}



export type user_accessSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  departments?: boolean
  access_right?: boolean
}, ExtArgs["result"]["user_access"]>



export type user_accessSelectScalar = {
  id?: boolean
  user_id?: boolean
  departments?: boolean
  access_right?: boolean
}

export type user_accessOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "departments" | "access_right", ExtArgs["result"]["user_access"]>

export type $user_accessPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "user_access"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    user_id: number
    departments: runtime.JsonValue | null
    access_right: number
  }, ExtArgs["result"]["user_access"]>
  composites: {}
}

export type user_accessGetPayload<S extends boolean | null | undefined | user_accessDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$user_accessPayload, S>

export type user_accessCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<user_accessFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: User_accessCountAggregateInputType | true
  }

export interface user_accessDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['user_access'], meta: { name: 'user_access' } }
  /**
   * Find zero or one User_access that matches the filter.
   * @param {user_accessFindUniqueArgs} args - Arguments to find a User_access
   * @example
   * // Get one User_access
   * const user_access = await prisma.user_access.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends user_accessFindUniqueArgs>(args: Prisma.SelectSubset<T, user_accessFindUniqueArgs<ExtArgs>>): Prisma.Prisma__user_accessClient<runtime.Types.Result.GetResult<Prisma.$user_accessPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User_access that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {user_accessFindUniqueOrThrowArgs} args - Arguments to find a User_access
   * @example
   * // Get one User_access
   * const user_access = await prisma.user_access.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends user_accessFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, user_accessFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__user_accessClient<runtime.Types.Result.GetResult<Prisma.$user_accessPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User_access that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_accessFindFirstArgs} args - Arguments to find a User_access
   * @example
   * // Get one User_access
   * const user_access = await prisma.user_access.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends user_accessFindFirstArgs>(args?: Prisma.SelectSubset<T, user_accessFindFirstArgs<ExtArgs>>): Prisma.Prisma__user_accessClient<runtime.Types.Result.GetResult<Prisma.$user_accessPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User_access that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_accessFindFirstOrThrowArgs} args - Arguments to find a User_access
   * @example
   * // Get one User_access
   * const user_access = await prisma.user_access.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends user_accessFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, user_accessFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__user_accessClient<runtime.Types.Result.GetResult<Prisma.$user_accessPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more User_accesses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_accessFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all User_accesses
   * const user_accesses = await prisma.user_access.findMany()
   * 
   * // Get first 10 User_accesses
   * const user_accesses = await prisma.user_access.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const user_accessWithIdOnly = await prisma.user_access.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends user_accessFindManyArgs>(args?: Prisma.SelectSubset<T, user_accessFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_accessPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User_access.
   * @param {user_accessCreateArgs} args - Arguments to create a User_access.
   * @example
   * // Create one User_access
   * const User_access = await prisma.user_access.create({
   *   data: {
   *     // ... data to create a User_access
   *   }
   * })
   * 
   */
  create<T extends user_accessCreateArgs>(args: Prisma.SelectSubset<T, user_accessCreateArgs<ExtArgs>>): Prisma.Prisma__user_accessClient<runtime.Types.Result.GetResult<Prisma.$user_accessPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many User_accesses.
   * @param {user_accessCreateManyArgs} args - Arguments to create many User_accesses.
   * @example
   * // Create many User_accesses
   * const user_access = await prisma.user_access.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends user_accessCreateManyArgs>(args?: Prisma.SelectSubset<T, user_accessCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a User_access.
   * @param {user_accessDeleteArgs} args - Arguments to delete one User_access.
   * @example
   * // Delete one User_access
   * const User_access = await prisma.user_access.delete({
   *   where: {
   *     // ... filter to delete one User_access
   *   }
   * })
   * 
   */
  delete<T extends user_accessDeleteArgs>(args: Prisma.SelectSubset<T, user_accessDeleteArgs<ExtArgs>>): Prisma.Prisma__user_accessClient<runtime.Types.Result.GetResult<Prisma.$user_accessPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User_access.
   * @param {user_accessUpdateArgs} args - Arguments to update one User_access.
   * @example
   * // Update one User_access
   * const user_access = await prisma.user_access.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends user_accessUpdateArgs>(args: Prisma.SelectSubset<T, user_accessUpdateArgs<ExtArgs>>): Prisma.Prisma__user_accessClient<runtime.Types.Result.GetResult<Prisma.$user_accessPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more User_accesses.
   * @param {user_accessDeleteManyArgs} args - Arguments to filter User_accesses to delete.
   * @example
   * // Delete a few User_accesses
   * const { count } = await prisma.user_access.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends user_accessDeleteManyArgs>(args?: Prisma.SelectSubset<T, user_accessDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more User_accesses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_accessUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many User_accesses
   * const user_access = await prisma.user_access.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends user_accessUpdateManyArgs>(args: Prisma.SelectSubset<T, user_accessUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one User_access.
   * @param {user_accessUpsertArgs} args - Arguments to update or create a User_access.
   * @example
   * // Update or create a User_access
   * const user_access = await prisma.user_access.upsert({
   *   create: {
   *     // ... data to create a User_access
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User_access we want to update
   *   }
   * })
   */
  upsert<T extends user_accessUpsertArgs>(args: Prisma.SelectSubset<T, user_accessUpsertArgs<ExtArgs>>): Prisma.Prisma__user_accessClient<runtime.Types.Result.GetResult<Prisma.$user_accessPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of User_accesses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_accessCountArgs} args - Arguments to filter User_accesses to count.
   * @example
   * // Count the number of User_accesses
   * const count = await prisma.user_access.count({
   *   where: {
   *     // ... the filter for the User_accesses we want to count
   *   }
   * })
  **/
  count<T extends user_accessCountArgs>(
    args?: Prisma.Subset<T, user_accessCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], User_accessCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User_access.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {User_accessAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends User_accessAggregateArgs>(args: Prisma.Subset<T, User_accessAggregateArgs>): Prisma.PrismaPromise<GetUser_accessAggregateType<T>>

  /**
   * Group by User_access.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_accessGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends user_accessGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: user_accessGroupByArgs['orderBy'] }
      : { orderBy?: user_accessGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, user_accessGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUser_accessGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the user_access model
 */
readonly fields: user_accessFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for user_access.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__user_accessClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the user_access model
 */
export interface user_accessFieldRefs {
  readonly id: Prisma.FieldRef<"user_access", 'Int'>
  readonly user_id: Prisma.FieldRef<"user_access", 'Int'>
  readonly departments: Prisma.FieldRef<"user_access", 'Json'>
  readonly access_right: Prisma.FieldRef<"user_access", 'Int'>
}
    

// Custom InputTypes
/**
 * user_access findUnique
 */
export type user_accessFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_access
   */
  select?: Prisma.user_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_access
   */
  omit?: Prisma.user_accessOmit<ExtArgs> | null
  /**
   * Filter, which user_access to fetch.
   */
  where: Prisma.user_accessWhereUniqueInput
}

/**
 * user_access findUniqueOrThrow
 */
export type user_accessFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_access
   */
  select?: Prisma.user_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_access
   */
  omit?: Prisma.user_accessOmit<ExtArgs> | null
  /**
   * Filter, which user_access to fetch.
   */
  where: Prisma.user_accessWhereUniqueInput
}

/**
 * user_access findFirst
 */
export type user_accessFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_access
   */
  select?: Prisma.user_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_access
   */
  omit?: Prisma.user_accessOmit<ExtArgs> | null
  /**
   * Filter, which user_access to fetch.
   */
  where?: Prisma.user_accessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_accesses to fetch.
   */
  orderBy?: Prisma.user_accessOrderByWithRelationInput | Prisma.user_accessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for user_accesses.
   */
  cursor?: Prisma.user_accessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_accesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_accesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of user_accesses.
   */
  distinct?: Prisma.User_accessScalarFieldEnum | Prisma.User_accessScalarFieldEnum[]
}

/**
 * user_access findFirstOrThrow
 */
export type user_accessFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_access
   */
  select?: Prisma.user_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_access
   */
  omit?: Prisma.user_accessOmit<ExtArgs> | null
  /**
   * Filter, which user_access to fetch.
   */
  where?: Prisma.user_accessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_accesses to fetch.
   */
  orderBy?: Prisma.user_accessOrderByWithRelationInput | Prisma.user_accessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for user_accesses.
   */
  cursor?: Prisma.user_accessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_accesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_accesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of user_accesses.
   */
  distinct?: Prisma.User_accessScalarFieldEnum | Prisma.User_accessScalarFieldEnum[]
}

/**
 * user_access findMany
 */
export type user_accessFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_access
   */
  select?: Prisma.user_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_access
   */
  omit?: Prisma.user_accessOmit<ExtArgs> | null
  /**
   * Filter, which user_accesses to fetch.
   */
  where?: Prisma.user_accessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_accesses to fetch.
   */
  orderBy?: Prisma.user_accessOrderByWithRelationInput | Prisma.user_accessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing user_accesses.
   */
  cursor?: Prisma.user_accessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_accesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_accesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of user_accesses.
   */
  distinct?: Prisma.User_accessScalarFieldEnum | Prisma.User_accessScalarFieldEnum[]
}

/**
 * user_access create
 */
export type user_accessCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_access
   */
  select?: Prisma.user_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_access
   */
  omit?: Prisma.user_accessOmit<ExtArgs> | null
  /**
   * The data needed to create a user_access.
   */
  data: Prisma.XOR<Prisma.user_accessCreateInput, Prisma.user_accessUncheckedCreateInput>
}

/**
 * user_access createMany
 */
export type user_accessCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many user_accesses.
   */
  data: Prisma.user_accessCreateManyInput | Prisma.user_accessCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * user_access update
 */
export type user_accessUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_access
   */
  select?: Prisma.user_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_access
   */
  omit?: Prisma.user_accessOmit<ExtArgs> | null
  /**
   * The data needed to update a user_access.
   */
  data: Prisma.XOR<Prisma.user_accessUpdateInput, Prisma.user_accessUncheckedUpdateInput>
  /**
   * Choose, which user_access to update.
   */
  where: Prisma.user_accessWhereUniqueInput
}

/**
 * user_access updateMany
 */
export type user_accessUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update user_accesses.
   */
  data: Prisma.XOR<Prisma.user_accessUpdateManyMutationInput, Prisma.user_accessUncheckedUpdateManyInput>
  /**
   * Filter which user_accesses to update
   */
  where?: Prisma.user_accessWhereInput
  /**
   * Limit how many user_accesses to update.
   */
  limit?: number
}

/**
 * user_access upsert
 */
export type user_accessUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_access
   */
  select?: Prisma.user_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_access
   */
  omit?: Prisma.user_accessOmit<ExtArgs> | null
  /**
   * The filter to search for the user_access to update in case it exists.
   */
  where: Prisma.user_accessWhereUniqueInput
  /**
   * In case the user_access found by the `where` argument doesn't exist, create a new user_access with this data.
   */
  create: Prisma.XOR<Prisma.user_accessCreateInput, Prisma.user_accessUncheckedCreateInput>
  /**
   * In case the user_access was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.user_accessUpdateInput, Prisma.user_accessUncheckedUpdateInput>
}

/**
 * user_access delete
 */
export type user_accessDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_access
   */
  select?: Prisma.user_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_access
   */
  omit?: Prisma.user_accessOmit<ExtArgs> | null
  /**
   * Filter which user_access to delete.
   */
  where: Prisma.user_accessWhereUniqueInput
}

/**
 * user_access deleteMany
 */
export type user_accessDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which user_accesses to delete
   */
  where?: Prisma.user_accessWhereInput
  /**
   * Limit how many user_accesses to delete.
   */
  limit?: number
}

/**
 * user_access without action
 */
export type user_accessDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_access
   */
  select?: Prisma.user_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_access
   */
  omit?: Prisma.user_accessOmit<ExtArgs> | null
}
