
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model access_rights
 * 
 */
export type access_rights = Prisma.access_rightsModel
/**
 * Model appointment_logs
 * 
 */
export type appointment_logs = Prisma.appointment_logsModel
/**
 * Model appointments
 * 
 */
export type appointments = Prisma.appointmentsModel
/**
 * Model department_schedule
 * 
 */
export type department_schedule = Prisma.department_scheduleModel
/**
 * Model departments
 * 
 */
export type departments = Prisma.departmentsModel
/**
 * Model holidays
 * 
 */
export type holidays = Prisma.holidaysModel
/**
 * Model patient_dependents
 * 
 */
export type patient_dependents = Prisma.patient_dependentsModel
/**
 * Model patients
 * 
 */
export type patients = Prisma.patientsModel
/**
 * Model user_access
 * 
 */
export type user_access = Prisma.user_accessModel
