
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const PriorityType = {
  EMPLOYEE: 'EMPLOYEE',
  SENIOR: 'SENIOR',
  PWD: 'PWD',
  PREGNANT: 'PREGNANT',
  REGULAR: 'REGULAR'
} as const

export type PriorityType = (typeof PriorityType)[keyof typeof PriorityType]
