
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/access_rights.js'
export type * from './models/appointment_logs.js'
export type * from './models/appointments.js'
export type * from './models/department_schedule.js'
export type * from './models/departments.js'
export type * from './models/holidays.js'
export type * from './models/patient_dependents.js'
export type * from './models/patients.js'
export type * from './models/user_access.js'
export type * from './commonInputTypes.js'