
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  access_rights: 'access_rights',
  appointment_logs: 'appointment_logs',
  appointments: 'appointments',
  department_schedule: 'department_schedule',
  departments: 'departments',
  holidays: 'holidays',
  patient_dependents: 'patient_dependents',
  patients: 'patients',
  user_access: 'user_access'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const Access_rightsScalarFieldEnum = {
  id: 'id',
  description: 'description',
  can_view_appointments: 'can_view_appointments',
  can_complete_appointment: 'can_complete_appointment',
  can_forward_appointment: 'can_forward_appointment',
  can_manage_department: 'can_manage_department',
  can_manage_access: 'can_manage_access',
  can_manage_holidays: 'can_manage_holidays'
} as const

export type Access_rightsScalarFieldEnum = (typeof Access_rightsScalarFieldEnum)[keyof typeof Access_rightsScalarFieldEnum]


export const Appointment_logsScalarFieldEnum = {
  id: 'id',
  appointment_id: 'appointment_id',
  action: 'action',
  remarks: 'remarks',
  created_at: 'created_at'
} as const

export type Appointment_logsScalarFieldEnum = (typeof Appointment_logsScalarFieldEnum)[keyof typeof Appointment_logsScalarFieldEnum]


export const AppointmentsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  patient_id: 'patient_id',
  department_id: 'department_id',
  step: 'step',
  scheduled_at: 'scheduled_at',
  complaint: 'complaint',
  type: 'type',
  subjective: 'subjective',
  objective: 'objective',
  assessment: 'assessment',
  plan: 'plan',
  assessed_by: 'assessed_by',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type AppointmentsScalarFieldEnum = (typeof AppointmentsScalarFieldEnum)[keyof typeof AppointmentsScalarFieldEnum]


export const Department_scheduleScalarFieldEnum = {
  id: 'id',
  dept_id: 'dept_id',
  days: 'days',
  start: 'start',
  end: 'end',
  pax: 'pax',
  type: 'type'
} as const

export type Department_scheduleScalarFieldEnum = (typeof Department_scheduleScalarFieldEnum)[keyof typeof Department_scheduleScalarFieldEnum]


export const DepartmentsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  description: 'description'
} as const

export type DepartmentsScalarFieldEnum = (typeof DepartmentsScalarFieldEnum)[keyof typeof DepartmentsScalarFieldEnum]


export const HolidaysScalarFieldEnum = {
  id: 'id',
  holiday: 'holiday',
  target: 'target',
  description: 'description'
} as const

export type HolidaysScalarFieldEnum = (typeof HolidaysScalarFieldEnum)[keyof typeof HolidaysScalarFieldEnum]


export const Patient_dependentsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  patient_id: 'patient_id'
} as const

export type Patient_dependentsScalarFieldEnum = (typeof Patient_dependentsScalarFieldEnum)[keyof typeof Patient_dependentsScalarFieldEnum]


export const PatientsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  owner_user_id: 'owner_user_id',
  relationship: 'relationship',
  fname: 'fname',
  mname: 'mname',
  lname: 'lname',
  email: 'email',
  ext_name: 'ext_name',
  birth_date: 'birth_date',
  civil_status: 'civil_status',
  sex: 'sex',
  religion: 'religion',
  nationality: 'nationality',
  occupation: 'occupation',
  lot_no: 'lot_no',
  street: 'street',
  barangay: 'barangay',
  city: 'city',
  province: 'province',
  mobile_no: 'mobile_no',
  spouse_name: 'spouse_name',
  spouse_address: 'spouse_address',
  father_name: 'father_name',
  mother_name: 'mother_name',
  created_at: 'created_at'
} as const

export type PatientsScalarFieldEnum = (typeof PatientsScalarFieldEnum)[keyof typeof PatientsScalarFieldEnum]


export const User_accessScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  departments: 'departments',
  access_right: 'access_right'
} as const

export type User_accessScalarFieldEnum = (typeof User_accessScalarFieldEnum)[keyof typeof User_accessScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const access_rightsOrderByRelevanceFieldEnum = {
  description: 'description'
} as const

export type access_rightsOrderByRelevanceFieldEnum = (typeof access_rightsOrderByRelevanceFieldEnum)[keyof typeof access_rightsOrderByRelevanceFieldEnum]


export const appointment_logsOrderByRelevanceFieldEnum = {
  action: 'action',
  remarks: 'remarks'
} as const

export type appointment_logsOrderByRelevanceFieldEnum = (typeof appointment_logsOrderByRelevanceFieldEnum)[keyof typeof appointment_logsOrderByRelevanceFieldEnum]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const appointmentsOrderByRelevanceFieldEnum = {
  complaint: 'complaint',
  type: 'type',
  subjective: 'subjective',
  objective: 'objective',
  assessment: 'assessment',
  plan: 'plan'
} as const

export type appointmentsOrderByRelevanceFieldEnum = (typeof appointmentsOrderByRelevanceFieldEnum)[keyof typeof appointmentsOrderByRelevanceFieldEnum]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const department_scheduleOrderByRelevanceFieldEnum = {
  type: 'type'
} as const

export type department_scheduleOrderByRelevanceFieldEnum = (typeof department_scheduleOrderByRelevanceFieldEnum)[keyof typeof department_scheduleOrderByRelevanceFieldEnum]


export const departmentsOrderByRelevanceFieldEnum = {
  name: 'name',
  code: 'code',
  description: 'description'
} as const

export type departmentsOrderByRelevanceFieldEnum = (typeof departmentsOrderByRelevanceFieldEnum)[keyof typeof departmentsOrderByRelevanceFieldEnum]


export const holidaysOrderByRelevanceFieldEnum = {
  description: 'description'
} as const

export type holidaysOrderByRelevanceFieldEnum = (typeof holidaysOrderByRelevanceFieldEnum)[keyof typeof holidaysOrderByRelevanceFieldEnum]


export const patientsOrderByRelevanceFieldEnum = {
  relationship: 'relationship',
  fname: 'fname',
  mname: 'mname',
  lname: 'lname',
  email: 'email',
  ext_name: 'ext_name',
  civil_status: 'civil_status',
  sex: 'sex',
  religion: 'religion',
  nationality: 'nationality',
  occupation: 'occupation',
  lot_no: 'lot_no',
  street: 'street',
  barangay: 'barangay',
  city: 'city',
  province: 'province',
  mobile_no: 'mobile_no',
  spouse_name: 'spouse_name',
  spouse_address: 'spouse_address',
  father_name: 'father_name',
  mother_name: 'mother_name'
} as const

export type patientsOrderByRelevanceFieldEnum = (typeof patientsOrderByRelevanceFieldEnum)[keyof typeof patientsOrderByRelevanceFieldEnum]

