
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models.js"
import { type PrismaClient } from "./class.js"

export type * from '../models.js'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
export const prismaVersion: PrismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  access_rights: 'access_rights',
  appointments: 'appointments',
  appointment_logs: 'appointment_logs',
  departments: 'departments',
  department_schedule: 'department_schedule',
  department_assignment: 'department_assignment',
  holidays: 'holidays',
  patient_dependents: 'patient_dependents',
  patients: 'patients',
  queue_sessions: 'queue_sessions',
  queue_session_stat: 'queue_session_stat',
  user_access: 'user_access'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "access_rights" | "appointments" | "appointment_logs" | "departments" | "department_schedule" | "department_assignment" | "holidays" | "patient_dependents" | "patients" | "queue_sessions" | "queue_session_stat" | "user_access"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    access_rights: {
      payload: Prisma.$access_rightsPayload<ExtArgs>
      fields: Prisma.access_rightsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.access_rightsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$access_rightsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.access_rightsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$access_rightsPayload>
        }
        findFirst: {
          args: Prisma.access_rightsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$access_rightsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.access_rightsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$access_rightsPayload>
        }
        findMany: {
          args: Prisma.access_rightsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$access_rightsPayload>[]
        }
        create: {
          args: Prisma.access_rightsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$access_rightsPayload>
        }
        createMany: {
          args: Prisma.access_rightsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.access_rightsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$access_rightsPayload>
        }
        update: {
          args: Prisma.access_rightsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$access_rightsPayload>
        }
        deleteMany: {
          args: Prisma.access_rightsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.access_rightsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.access_rightsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$access_rightsPayload>
        }
        aggregate: {
          args: Prisma.Access_rightsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAccess_rights>
        }
        groupBy: {
          args: Prisma.access_rightsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Access_rightsGroupByOutputType>[]
        }
        count: {
          args: Prisma.access_rightsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Access_rightsCountAggregateOutputType> | number
        }
      }
    }
    appointments: {
      payload: Prisma.$appointmentsPayload<ExtArgs>
      fields: Prisma.appointmentsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.appointmentsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointmentsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.appointmentsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointmentsPayload>
        }
        findFirst: {
          args: Prisma.appointmentsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointmentsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.appointmentsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointmentsPayload>
        }
        findMany: {
          args: Prisma.appointmentsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointmentsPayload>[]
        }
        create: {
          args: Prisma.appointmentsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointmentsPayload>
        }
        createMany: {
          args: Prisma.appointmentsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.appointmentsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointmentsPayload>
        }
        update: {
          args: Prisma.appointmentsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointmentsPayload>
        }
        deleteMany: {
          args: Prisma.appointmentsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.appointmentsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.appointmentsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointmentsPayload>
        }
        aggregate: {
          args: Prisma.AppointmentsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAppointments>
        }
        groupBy: {
          args: Prisma.appointmentsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AppointmentsGroupByOutputType>[]
        }
        count: {
          args: Prisma.appointmentsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AppointmentsCountAggregateOutputType> | number
        }
      }
    }
    appointment_logs: {
      payload: Prisma.$appointment_logsPayload<ExtArgs>
      fields: Prisma.appointment_logsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.appointment_logsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointment_logsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.appointment_logsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointment_logsPayload>
        }
        findFirst: {
          args: Prisma.appointment_logsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointment_logsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.appointment_logsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointment_logsPayload>
        }
        findMany: {
          args: Prisma.appointment_logsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointment_logsPayload>[]
        }
        create: {
          args: Prisma.appointment_logsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointment_logsPayload>
        }
        createMany: {
          args: Prisma.appointment_logsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.appointment_logsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointment_logsPayload>
        }
        update: {
          args: Prisma.appointment_logsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointment_logsPayload>
        }
        deleteMany: {
          args: Prisma.appointment_logsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.appointment_logsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.appointment_logsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointment_logsPayload>
        }
        aggregate: {
          args: Prisma.Appointment_logsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAppointment_logs>
        }
        groupBy: {
          args: Prisma.appointment_logsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Appointment_logsGroupByOutputType>[]
        }
        count: {
          args: Prisma.appointment_logsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Appointment_logsCountAggregateOutputType> | number
        }
      }
    }
    departments: {
      payload: Prisma.$departmentsPayload<ExtArgs>
      fields: Prisma.departmentsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.departmentsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.departmentsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload>
        }
        findFirst: {
          args: Prisma.departmentsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.departmentsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload>
        }
        findMany: {
          args: Prisma.departmentsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload>[]
        }
        create: {
          args: Prisma.departmentsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload>
        }
        createMany: {
          args: Prisma.departmentsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.departmentsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload>
        }
        update: {
          args: Prisma.departmentsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload>
        }
        deleteMany: {
          args: Prisma.departmentsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.departmentsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.departmentsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload>
        }
        aggregate: {
          args: Prisma.DepartmentsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDepartments>
        }
        groupBy: {
          args: Prisma.departmentsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DepartmentsGroupByOutputType>[]
        }
        count: {
          args: Prisma.departmentsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DepartmentsCountAggregateOutputType> | number
        }
      }
    }
    department_schedule: {
      payload: Prisma.$department_schedulePayload<ExtArgs>
      fields: Prisma.department_scheduleFieldRefs
      operations: {
        findUnique: {
          args: Prisma.department_scheduleFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$department_schedulePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.department_scheduleFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$department_schedulePayload>
        }
        findFirst: {
          args: Prisma.department_scheduleFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$department_schedulePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.department_scheduleFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$department_schedulePayload>
        }
        findMany: {
          args: Prisma.department_scheduleFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$department_schedulePayload>[]
        }
        create: {
          args: Prisma.department_scheduleCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$department_schedulePayload>
        }
        createMany: {
          args: Prisma.department_scheduleCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.department_scheduleDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$department_schedulePayload>
        }
        update: {
          args: Prisma.department_scheduleUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$department_schedulePayload>
        }
        deleteMany: {
          args: Prisma.department_scheduleDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.department_scheduleUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.department_scheduleUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$department_schedulePayload>
        }
        aggregate: {
          args: Prisma.Department_scheduleAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDepartment_schedule>
        }
        groupBy: {
          args: Prisma.department_scheduleGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Department_scheduleGroupByOutputType>[]
        }
        count: {
          args: Prisma.department_scheduleCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Department_scheduleCountAggregateOutputType> | number
        }
      }
    }
    department_assignment: {
      payload: Prisma.$department_assignmentPayload<ExtArgs>
      fields: Prisma.department_assignmentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.department_assignmentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$department_assignmentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.department_assignmentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$department_assignmentPayload>
        }
        findFirst: {
          args: Prisma.department_assignmentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$department_assignmentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.department_assignmentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$department_assignmentPayload>
        }
        findMany: {
          args: Prisma.department_assignmentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$department_assignmentPayload>[]
        }
        create: {
          args: Prisma.department_assignmentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$department_assignmentPayload>
        }
        createMany: {
          args: Prisma.department_assignmentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.department_assignmentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$department_assignmentPayload>
        }
        update: {
          args: Prisma.department_assignmentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$department_assignmentPayload>
        }
        deleteMany: {
          args: Prisma.department_assignmentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.department_assignmentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.department_assignmentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$department_assignmentPayload>
        }
        aggregate: {
          args: Prisma.Department_assignmentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDepartment_assignment>
        }
        groupBy: {
          args: Prisma.department_assignmentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Department_assignmentGroupByOutputType>[]
        }
        count: {
          args: Prisma.department_assignmentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Department_assignmentCountAggregateOutputType> | number
        }
      }
    }
    holidays: {
      payload: Prisma.$holidaysPayload<ExtArgs>
      fields: Prisma.holidaysFieldRefs
      operations: {
        findUnique: {
          args: Prisma.holidaysFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$holidaysPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.holidaysFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$holidaysPayload>
        }
        findFirst: {
          args: Prisma.holidaysFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$holidaysPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.holidaysFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$holidaysPayload>
        }
        findMany: {
          args: Prisma.holidaysFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$holidaysPayload>[]
        }
        create: {
          args: Prisma.holidaysCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$holidaysPayload>
        }
        createMany: {
          args: Prisma.holidaysCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.holidaysDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$holidaysPayload>
        }
        update: {
          args: Prisma.holidaysUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$holidaysPayload>
        }
        deleteMany: {
          args: Prisma.holidaysDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.holidaysUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.holidaysUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$holidaysPayload>
        }
        aggregate: {
          args: Prisma.HolidaysAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateHolidays>
        }
        groupBy: {
          args: Prisma.holidaysGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.HolidaysGroupByOutputType>[]
        }
        count: {
          args: Prisma.holidaysCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.HolidaysCountAggregateOutputType> | number
        }
      }
    }
    patient_dependents: {
      payload: Prisma.$patient_dependentsPayload<ExtArgs>
      fields: Prisma.patient_dependentsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.patient_dependentsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$patient_dependentsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.patient_dependentsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$patient_dependentsPayload>
        }
        findFirst: {
          args: Prisma.patient_dependentsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$patient_dependentsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.patient_dependentsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$patient_dependentsPayload>
        }
        findMany: {
          args: Prisma.patient_dependentsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$patient_dependentsPayload>[]
        }
        create: {
          args: Prisma.patient_dependentsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$patient_dependentsPayload>
        }
        createMany: {
          args: Prisma.patient_dependentsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.patient_dependentsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$patient_dependentsPayload>
        }
        update: {
          args: Prisma.patient_dependentsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$patient_dependentsPayload>
        }
        deleteMany: {
          args: Prisma.patient_dependentsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.patient_dependentsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.patient_dependentsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$patient_dependentsPayload>
        }
        aggregate: {
          args: Prisma.Patient_dependentsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePatient_dependents>
        }
        groupBy: {
          args: Prisma.patient_dependentsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Patient_dependentsGroupByOutputType>[]
        }
        count: {
          args: Prisma.patient_dependentsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Patient_dependentsCountAggregateOutputType> | number
        }
      }
    }
    patients: {
      payload: Prisma.$patientsPayload<ExtArgs>
      fields: Prisma.patientsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.patientsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$patientsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.patientsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$patientsPayload>
        }
        findFirst: {
          args: Prisma.patientsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$patientsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.patientsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$patientsPayload>
        }
        findMany: {
          args: Prisma.patientsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$patientsPayload>[]
        }
        create: {
          args: Prisma.patientsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$patientsPayload>
        }
        createMany: {
          args: Prisma.patientsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.patientsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$patientsPayload>
        }
        update: {
          args: Prisma.patientsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$patientsPayload>
        }
        deleteMany: {
          args: Prisma.patientsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.patientsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.patientsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$patientsPayload>
        }
        aggregate: {
          args: Prisma.PatientsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePatients>
        }
        groupBy: {
          args: Prisma.patientsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PatientsGroupByOutputType>[]
        }
        count: {
          args: Prisma.patientsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PatientsCountAggregateOutputType> | number
        }
      }
    }
    queue_sessions: {
      payload: Prisma.$queue_sessionsPayload<ExtArgs>
      fields: Prisma.queue_sessionsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.queue_sessionsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_sessionsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.queue_sessionsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_sessionsPayload>
        }
        findFirst: {
          args: Prisma.queue_sessionsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_sessionsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.queue_sessionsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_sessionsPayload>
        }
        findMany: {
          args: Prisma.queue_sessionsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_sessionsPayload>[]
        }
        create: {
          args: Prisma.queue_sessionsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_sessionsPayload>
        }
        createMany: {
          args: Prisma.queue_sessionsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.queue_sessionsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_sessionsPayload>
        }
        update: {
          args: Prisma.queue_sessionsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_sessionsPayload>
        }
        deleteMany: {
          args: Prisma.queue_sessionsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.queue_sessionsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.queue_sessionsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_sessionsPayload>
        }
        aggregate: {
          args: Prisma.Queue_sessionsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateQueue_sessions>
        }
        groupBy: {
          args: Prisma.queue_sessionsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Queue_sessionsGroupByOutputType>[]
        }
        count: {
          args: Prisma.queue_sessionsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Queue_sessionsCountAggregateOutputType> | number
        }
      }
    }
    queue_session_stat: {
      payload: Prisma.$queue_session_statPayload<ExtArgs>
      fields: Prisma.queue_session_statFieldRefs
      operations: {
        findUnique: {
          args: Prisma.queue_session_statFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_session_statPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.queue_session_statFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_session_statPayload>
        }
        findFirst: {
          args: Prisma.queue_session_statFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_session_statPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.queue_session_statFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_session_statPayload>
        }
        findMany: {
          args: Prisma.queue_session_statFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_session_statPayload>[]
        }
        create: {
          args: Prisma.queue_session_statCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_session_statPayload>
        }
        createMany: {
          args: Prisma.queue_session_statCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.queue_session_statDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_session_statPayload>
        }
        update: {
          args: Prisma.queue_session_statUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_session_statPayload>
        }
        deleteMany: {
          args: Prisma.queue_session_statDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.queue_session_statUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.queue_session_statUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_session_statPayload>
        }
        aggregate: {
          args: Prisma.Queue_session_statAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateQueue_session_stat>
        }
        groupBy: {
          args: Prisma.queue_session_statGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Queue_session_statGroupByOutputType>[]
        }
        count: {
          args: Prisma.queue_session_statCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Queue_session_statCountAggregateOutputType> | number
        }
      }
    }
    user_access: {
      payload: Prisma.$user_accessPayload<ExtArgs>
      fields: Prisma.user_accessFieldRefs
      operations: {
        findUnique: {
          args: Prisma.user_accessFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$user_accessPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.user_accessFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$user_accessPayload>
        }
        findFirst: {
          args: Prisma.user_accessFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$user_accessPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.user_accessFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$user_accessPayload>
        }
        findMany: {
          args: Prisma.user_accessFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$user_accessPayload>[]
        }
        create: {
          args: Prisma.user_accessCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$user_accessPayload>
        }
        createMany: {
          args: Prisma.user_accessCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.user_accessDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$user_accessPayload>
        }
        update: {
          args: Prisma.user_accessUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$user_accessPayload>
        }
        deleteMany: {
          args: Prisma.user_accessDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.user_accessUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.user_accessUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$user_accessPayload>
        }
        aggregate: {
          args: Prisma.User_accessAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser_access>
        }
        groupBy: {
          args: Prisma.user_accessGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.User_accessGroupByOutputType>[]
        }
        count: {
          args: Prisma.user_accessCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.User_accessCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const Access_rightsScalarFieldEnum = {
  id: 'id',
  description: 'description',
  can_complete_appt: 'can_complete_appt',
  can_manage_appts: 'can_manage_appts',
  can_manage_departments: 'can_manage_departments',
  can_manage_access: 'can_manage_access',
  can_manage_holidays: 'can_manage_holidays',
  can_manage_queue: 'can_manage_queue',
  can_view_all_appts: 'can_view_all_appts'
} as const

export type Access_rightsScalarFieldEnum = (typeof Access_rightsScalarFieldEnum)[keyof typeof Access_rightsScalarFieldEnum]


export const AppointmentsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  patient_id: 'patient_id',
  dept_id: 'dept_id',
  step: 'step',
  scheduled_at: 'scheduled_at',
  complaint: 'complaint',
  type: 'type',
  subjective: 'subjective',
  objective: 'objective',
  assessment: 'assessment',
  plan: 'plan',
  assessed_by: 'assessed_by',
  ai_assisted: 'ai_assisted',
  status: 'status',
  queue_no: 'queue_no',
  created_at: 'created_at'
} as const

export type AppointmentsScalarFieldEnum = (typeof AppointmentsScalarFieldEnum)[keyof typeof AppointmentsScalarFieldEnum]


export const Appointment_logsScalarFieldEnum = {
  id: 'id',
  appointment_id: 'appointment_id',
  action: 'action',
  remarks: 'remarks',
  created_at: 'created_at'
} as const

export type Appointment_logsScalarFieldEnum = (typeof Appointment_logsScalarFieldEnum)[keyof typeof Appointment_logsScalarFieldEnum]


export const DepartmentsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  description: 'description'
} as const

export type DepartmentsScalarFieldEnum = (typeof DepartmentsScalarFieldEnum)[keyof typeof DepartmentsScalarFieldEnum]


export const Department_scheduleScalarFieldEnum = {
  id: 'id',
  dept_id: 'dept_id',
  days: 'days',
  start: 'start',
  end: 'end',
  pax: 'pax',
  type: 'type'
} as const

export type Department_scheduleScalarFieldEnum = (typeof Department_scheduleScalarFieldEnum)[keyof typeof Department_scheduleScalarFieldEnum]


export const Department_assignmentScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  dept_id: 'dept_id'
} as const

export type Department_assignmentScalarFieldEnum = (typeof Department_assignmentScalarFieldEnum)[keyof typeof Department_assignmentScalarFieldEnum]


export const HolidaysScalarFieldEnum = {
  id: 'id',
  holiday: 'holiday',
  target: 'target',
  description: 'description'
} as const

export type HolidaysScalarFieldEnum = (typeof HolidaysScalarFieldEnum)[keyof typeof HolidaysScalarFieldEnum]


export const Patient_dependentsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  patient_id: 'patient_id'
} as const

export type Patient_dependentsScalarFieldEnum = (typeof Patient_dependentsScalarFieldEnum)[keyof typeof Patient_dependentsScalarFieldEnum]


export const PatientsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  owner_user_id: 'owner_user_id',
  relationship: 'relationship',
  fname: 'fname',
  mname: 'mname',
  lname: 'lname',
  email: 'email',
  ext_name: 'ext_name',
  birth_date: 'birth_date',
  civil_status: 'civil_status',
  sex: 'sex',
  religion: 'religion',
  nationality: 'nationality',
  occupation: 'occupation',
  lot_no: 'lot_no',
  street: 'street',
  barangay: 'barangay',
  city: 'city',
  province: 'province',
  mobile_no: 'mobile_no',
  spouse_name: 'spouse_name',
  spouse_address: 'spouse_address',
  father_name: 'father_name',
  mother_name: 'mother_name',
  created_at: 'created_at'
} as const

export type PatientsScalarFieldEnum = (typeof PatientsScalarFieldEnum)[keyof typeof PatientsScalarFieldEnum]


export const Queue_sessionsScalarFieldEnum = {
  id: 'id',
  dept_id: 'dept_id',
  session_date: 'session_date',
  has_started: 'has_started',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Queue_sessionsScalarFieldEnum = (typeof Queue_sessionsScalarFieldEnum)[keyof typeof Queue_sessionsScalarFieldEnum]


export const Queue_session_statScalarFieldEnum = {
  id: 'id',
  session_id: 'session_id',
  step: 'step',
  now_serving: 'now_serving',
  served_count: 'served_count',
  avg_seconds: 'avg_seconds',
  updated_at: 'updated_at'
} as const

export type Queue_session_statScalarFieldEnum = (typeof Queue_session_statScalarFieldEnum)[keyof typeof Queue_session_statScalarFieldEnum]


export const User_accessScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  departments: 'departments',
  access_right: 'access_right'
} as const

export type User_accessScalarFieldEnum = (typeof User_accessScalarFieldEnum)[keyof typeof User_accessScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const access_rightsOrderByRelevanceFieldEnum = {
  description: 'description'
} as const

export type access_rightsOrderByRelevanceFieldEnum = (typeof access_rightsOrderByRelevanceFieldEnum)[keyof typeof access_rightsOrderByRelevanceFieldEnum]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const appointmentsOrderByRelevanceFieldEnum = {
  complaint: 'complaint',
  type: 'type',
  subjective: 'subjective',
  objective: 'objective',
  assessment: 'assessment',
  plan: 'plan',
  status: 'status'
} as const

export type appointmentsOrderByRelevanceFieldEnum = (typeof appointmentsOrderByRelevanceFieldEnum)[keyof typeof appointmentsOrderByRelevanceFieldEnum]


export const appointment_logsOrderByRelevanceFieldEnum = {
  action: 'action',
  remarks: 'remarks'
} as const

export type appointment_logsOrderByRelevanceFieldEnum = (typeof appointment_logsOrderByRelevanceFieldEnum)[keyof typeof appointment_logsOrderByRelevanceFieldEnum]


export const departmentsOrderByRelevanceFieldEnum = {
  name: 'name',
  code: 'code',
  description: 'description'
} as const

export type departmentsOrderByRelevanceFieldEnum = (typeof departmentsOrderByRelevanceFieldEnum)[keyof typeof departmentsOrderByRelevanceFieldEnum]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const department_scheduleOrderByRelevanceFieldEnum = {
  type: 'type'
} as const

export type department_scheduleOrderByRelevanceFieldEnum = (typeof department_scheduleOrderByRelevanceFieldEnum)[keyof typeof department_scheduleOrderByRelevanceFieldEnum]


export const holidaysOrderByRelevanceFieldEnum = {
  description: 'description'
} as const

export type holidaysOrderByRelevanceFieldEnum = (typeof holidaysOrderByRelevanceFieldEnum)[keyof typeof holidaysOrderByRelevanceFieldEnum]


export const patientsOrderByRelevanceFieldEnum = {
  relationship: 'relationship',
  fname: 'fname',
  mname: 'mname',
  lname: 'lname',
  email: 'email',
  ext_name: 'ext_name',
  civil_status: 'civil_status',
  sex: 'sex',
  religion: 'religion',
  nationality: 'nationality',
  occupation: 'occupation',
  lot_no: 'lot_no',
  street: 'street',
  barangay: 'barangay',
  city: 'city',
  province: 'province',
  mobile_no: 'mobile_no',
  spouse_name: 'spouse_name',
  spouse_address: 'spouse_address',
  father_name: 'father_name',
  mother_name: 'mother_name'
} as const

export type patientsOrderByRelevanceFieldEnum = (typeof patientsOrderByRelevanceFieldEnum)[keyof typeof patientsOrderByRelevanceFieldEnum]



/**
 * Field references
 */


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'Json'
 */
export type JsonFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Json'>
    


/**
 * Reference to a field of type 'QueryMode'
 */
export type EnumQueryModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'QueryMode'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
  /**
   * Optional maximum size for the query plan cache. If not provided, a default size will be used.
   * A value of `0` can be used to disable the cache entirely. A higher cache size can improve
   * performance for applications that execute a large number of unique queries, while a smaller
   * cache size can reduce memory usage.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   queryPlanCacheMaxSize: 100,
   * })
   * ```
   */
  queryPlanCacheMaxSize?: number
}
export type GlobalOmitConfig = {
  access_rights?: Prisma.access_rightsOmit
  appointments?: Prisma.appointmentsOmit
  appointment_logs?: Prisma.appointment_logsOmit
  departments?: Prisma.departmentsOmit
  department_schedule?: Prisma.department_scheduleOmit
  department_assignment?: Prisma.department_assignmentOmit
  holidays?: Prisma.holidaysOmit
  patient_dependents?: Prisma.patient_dependentsOmit
  patients?: Prisma.patientsOmit
  queue_sessions?: Prisma.queue_sessionsOmit
  queue_session_stat?: Prisma.queue_session_statOmit
  user_access?: Prisma.user_accessOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

